{"timestamp":"2024-02-26 14:36:54.399","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"j.l.IllegalStateException: Ambiguous mapping. Cannot map 'accountController' method \nkr.co.jsol.api.controller.AccountController#createAccount()\nto {POST [/api/v1/account]}: There is already 'accountController' bean method\nkr.co.jsol.api.controller.AccountController#cr() mapped.\n\tat o.s.w.s.h.AbstractHandlerMethodMapping$MappingRegistry.validateMethodMapping(AbstractHandlerMethodMapping.java:669)\n\tat o.s.w.s.h.AbstractHandlerMethodMapping$MappingRegistry.register(AbstractHandlerMethodMapping.java:635)\n\tat o.s.w.s.h.AbstractHandlerMethodMapping.registerHandlerMethod(AbstractHandlerMethodMapping.java:332)\n\tat o.s.w.s.m.m.a.RequestMappingHandlerMapping.registerHandlerMethod(RequestMappingHandlerMapping.java:420)\n\tat o.s.w.s.m.m.a.RequestMappingHandlerMapping.registerHandlerMethod(RequestMappingHandlerMapping.java:76)\n\tat o.s.w.s.h.AbstractHandlerMethodMapping.lambda$detectHandlerMethods$2(AbstractHandlerMethodMapping.java:299)\n\tat j.util.LinkedHashMap.forEach(LinkedHashMap.java:721)\n\tat o.s.w.s.h.AbstractHandlerMethodMapping.detectHandlerMethods(AbstractHandlerMethodMapping.java:297)\n\tat o.s.w.s.h.AbstractHandlerMethodMapping.processCandidateBean(AbstractHandlerMethodMapping.java:266)\n\tat o.s.w.s.h.AbstractHandlerMethodMapping.initHandlerMethods(AbstractHandlerMethodMapping.java:225)\n\tat o.s.w.s.h.AbstractHandlerMethodMapping.afterPropertiesSet(AbstractHandlerMethodMapping.java:213)\n\tat o.s.w.s.m.m.a.RequestMappingHandlerMapping.afterPropertiesSet(RequestMappingHandlerMapping.java:205)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)\n\t... 21 common frames omitted\nWrapped by: o.s.b.f.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nest...\n"}
{"timestamp":"2024-02-26 14:42:25.664","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-8","traceId":"6ae24be206c5985738e1e6c38bc4a1ae","spanId":"630bcd97043fe3d4","message":"illegalArgumentExceptionHandler - message : Illegal character in scheme name at index 0: %20https://localhost:11001/users"}
{"timestamp":"2024-02-26 14:43:20.972","logger":"com.zaxxer.hikari.pool.HikariPool","level":"ERROR","thread":"restartedMain","message":"HikariPool-1 - Exception during pool initialization.","stack_trace":"j.n.ConnectException: Connection refused\n\tat sun.nio.ch.Net.pollConnect(Net.java)\n\tat sun.nio.ch.Net.pollConnectNow(Net.java:672)\n\tat s.n.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:547)\n\tat s.n.ch.NioSocketImpl.connect(NioSocketImpl.java:602)\n\tat j.n.SocksSocketImpl.connect(SocksSocketImpl.java:327)\n\tat java.net.Socket.connect(Socket.java:633)\n\tat o.m.j.c.i.ConnectionHelper.connectSocket(ConnectionHelper.java:131)\n\t... 92 common frames omitted\nWrapped by: j.s.SQLNonTransientConnectionException: Socket fail to connect to host:address=(host=localhost)(port=3306)(type=primary). Connection refused\n\tat o.m.j.c.i.ConnectionHelper.connectSocket(ConnectionHelper.java:137)\n\tat o.m.j.c.i.StandardClient.<init>(StandardClient.java:99)\n\tat o.m.jdbc.Driver.connect(Driver.java:70)\n\tat o.m.jdbc.Driver.connect(Driver.java:101)\n\tat o.m.jdbc.Driver.connect(Driver.java:27)\n\tat c.z.h.u.DriverDataSource.getConnection(DriverDataSource.java:138)\n\tat c.z.h.pool.PoolBase.newConnection(PoolBase.java:364)\n\tat c.z.h.pool.PoolBase.newPoolEntry(PoolBase.java:206)\n\tat c.z.h.p.HikariPool.createPoolEntry(HikariPool.java:476)\n\tat c.z.h.p.HikariPool.checkFailFast(HikariPool.java:561)\n\tat c.z.h.p.HikariPool.<init>(HikariPool.java:115)\n\tat c.z.h.HikariDataSource.getConnection(HikariDataSource.java:112)\n\tat o.s.b.a.h.H2ConsoleAutoConfiguration.lambda$logDataSources$1(H2ConsoleAutoConfiguration.java:86)\n\tat j.u.s.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)\n\tat java.util.ArrayList.forEach(ArrayList.java:1511)\n\tat j.u.s.SortedOps$RefSortingSink.end(SortedOps.java:395)\n\tat j.u.s.Sink$ChainedReference.end(Sink.java:258)\n\tat j.u.s.Sink$ChainedReference.end(Sink.java:258)\n\tat j.u.s.AbstractPipeline.copyInto(AbstractPipeline.java:510)\n\tat j.u.s.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)\n\tat j.u.s.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)\n\tat j.u.s.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n\tat j.u.s.ReferencePipeline.collect(ReferencePipeline.java:682)\n\tat o.s.b.a.h.H2ConsoleAutoConfigura...\n"}
{"timestamp":"2024-02-26 14:43:22.348","logger":"com.zaxxer.hikari.pool.HikariPool","level":"ERROR","thread":"restartedMain","message":"HikariPool-1 - Exception during pool initialization.","stack_trace":"j.n.ConnectException: Connection refused\n\tat sun.nio.ch.Net.pollConnect(Net.java)\n\tat sun.nio.ch.Net.pollConnectNow(Net.java:672)\n\tat s.n.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:554)\n\tat s.n.ch.NioSocketImpl.connect(NioSocketImpl.java:602)\n\tat j.n.SocksSocketImpl.connect(SocksSocketImpl.java:327)\n\tat java.net.Socket.connect(Socket.java:633)\n\tat o.m.j.c.i.ConnectionHelper.connectSocket(ConnectionHelper.java:131)\n\t... 166 common frames omitted\nWrapped by: j.s.SQLNonTransientConnectionException: Socket fail to connect to host:address=(host=localhost)(port=3306)(type=primary). Connection refused\n\tat o.m.j.c.i.ConnectionHelper.connectSocket(ConnectionHelper.java:137)\n\tat o.m.j.c.i.StandardClient.<init>(StandardClient.java:99)\n\tat o.m.jdbc.Driver.connect(Driver.java:70)\n\tat o.m.jdbc.Driver.connect(Driver.java:101)\n\tat o.m.jdbc.Driver.connect(Driver.java:27)\n\tat c.z.h.u.DriverDataSource.getConnection(DriverDataSource.java:138)\n\tat c.z.h.pool.PoolBase.newConnection(PoolBase.java:364)\n\tat c.z.h.pool.PoolBase.newPoolEntry(PoolBase.java:206)\n\tat c.z.h.p.HikariPool.createPoolEntry(HikariPool.java:476)\n\tat c.z.h.p.HikariPool.checkFailFast(HikariPool.java:561)\n\tat c.z.h.p.HikariPool.<init>(HikariPool.java:115)\n\tat c.z.h.HikariDataSource.getConnection(HikariDataSource.java:112)\n\tat o.h.e.j.c.i.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:181)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)\n\tat o.h.b.r.i.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)\n\tat o.h.s.i.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:272)\n\tat o.h.s.i.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246)\n\tat o.h.s.i.AbstractServiceRegistryImpl.g...\n"}
{"timestamp":"2024-02-26 14:43:22.352","logger":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"ERROR","thread":"restartedMain","message":"Failed to initialize JPA EntityManagerFactory: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]"}
{"timestamp":"2024-02-26 14:43:22.354","logger":"org.springframework.boot.web.embedded.tomcat.TomcatStarter","level":"ERROR","thread":"restartedMain","message":"Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'jwtAuthenticationFilter' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtAuthenticationFilter.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jwtService' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userDetailsServiceImpl' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/domain/build/classes/kotlin/main/kr/co/jsol/domain/userdetails/UserDetailsServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'accountQueryRepository' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/domain/build/classes/kotlin/main/kr/co/jsol/domain/account/infrastructure/query/AccountQueryRepository.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accountRepository' defined in kr.co.jsol.domain.account.infrastructure.repository.AccountRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Cannot create inner bean '(inner bean)#115da3c6' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#115da3c6': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]"}
{"timestamp":"2024-02-26 14:43:22.408","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"o.h.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set\n\tat o.h.e.j.d.i.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:100)\n\tat o.h.e.j.d.i.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:54)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:138)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)\n\tat o.h.b.r.i.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)\n\tat o.h.s.i.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:272)\n\t... 149 common frames omitted\nWrapped by: o.h.s.s.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]\n\tat o.h.s.i.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:284)\n\tat o.h.s.i.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246)\n\tat o.h.s.i.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:223)\n\tat o.h.i.f.i.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:175)\n\tat o.h.s.i.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:295)\n\tat o.h.s.i.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:252)\n\tat o.h.s.i.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:223)\n\tat o.h.b.i.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:173)\n\tat o.h.b.m.p.s.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:127)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)\n\tat o.s.o.j.v.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalC...\n"}
{"timestamp":"2024-02-26 14:43:43.753","logger":"com.zaxxer.hikari.pool.HikariPool","level":"ERROR","thread":"restartedMain","message":"HikariPool-1 - Exception during pool initialization.","stack_trace":"j.n.ConnectException: Connection refused\n\tat sun.nio.ch.Net.pollConnect(Net.java)\n\tat sun.nio.ch.Net.pollConnectNow(Net.java:672)\n\tat s.n.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:547)\n\tat s.n.ch.NioSocketImpl.connect(NioSocketImpl.java:602)\n\tat j.n.SocksSocketImpl.connect(SocksSocketImpl.java:327)\n\tat java.net.Socket.connect(Socket.java:633)\n\tat o.m.j.c.i.ConnectionHelper.connectSocket(ConnectionHelper.java:131)\n\t... 92 common frames omitted\nWrapped by: j.s.SQLNonTransientConnectionException: Socket fail to connect to host:address=(host=localhost)(port=3306)(type=primary). Connection refused\n\tat o.m.j.c.i.ConnectionHelper.connectSocket(ConnectionHelper.java:137)\n\tat o.m.j.c.i.StandardClient.<init>(StandardClient.java:99)\n\tat o.m.jdbc.Driver.connect(Driver.java:70)\n\tat o.m.jdbc.Driver.connect(Driver.java:101)\n\tat o.m.jdbc.Driver.connect(Driver.java:27)\n\tat c.z.h.u.DriverDataSource.getConnection(DriverDataSource.java:138)\n\tat c.z.h.pool.PoolBase.newConnection(PoolBase.java:364)\n\tat c.z.h.pool.PoolBase.newPoolEntry(PoolBase.java:206)\n\tat c.z.h.p.HikariPool.createPoolEntry(HikariPool.java:476)\n\tat c.z.h.p.HikariPool.checkFailFast(HikariPool.java:561)\n\tat c.z.h.p.HikariPool.<init>(HikariPool.java:115)\n\tat c.z.h.HikariDataSource.getConnection(HikariDataSource.java:112)\n\tat o.s.b.a.h.H2ConsoleAutoConfiguration.lambda$logDataSources$1(H2ConsoleAutoConfiguration.java:86)\n\tat j.u.s.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)\n\tat java.util.ArrayList.forEach(ArrayList.java:1511)\n\tat j.u.s.SortedOps$RefSortingSink.end(SortedOps.java:395)\n\tat j.u.s.Sink$ChainedReference.end(Sink.java:258)\n\tat j.u.s.Sink$ChainedReference.end(Sink.java:258)\n\tat j.u.s.AbstractPipeline.copyInto(AbstractPipeline.java:510)\n\tat j.u.s.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)\n\tat j.u.s.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)\n\tat j.u.s.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n\tat j.u.s.ReferencePipeline.collect(ReferencePipeline.java:682)\n\tat o.s.b.a.h.H2ConsoleAutoConfigura...\n"}
{"timestamp":"2024-02-26 14:43:45.136","logger":"com.zaxxer.hikari.pool.HikariPool","level":"ERROR","thread":"restartedMain","message":"HikariPool-1 - Exception during pool initialization.","stack_trace":"j.n.ConnectException: Connection refused\n\tat sun.nio.ch.Net.pollConnect(Net.java)\n\tat sun.nio.ch.Net.pollConnectNow(Net.java:672)\n\tat s.n.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:554)\n\tat s.n.ch.NioSocketImpl.connect(NioSocketImpl.java:602)\n\tat j.n.SocksSocketImpl.connect(SocksSocketImpl.java:327)\n\tat java.net.Socket.connect(Socket.java:633)\n\tat o.m.j.c.i.ConnectionHelper.connectSocket(ConnectionHelper.java:131)\n\t... 166 common frames omitted\nWrapped by: j.s.SQLNonTransientConnectionException: Socket fail to connect to host:address=(host=localhost)(port=3306)(type=primary). Connection refused\n\tat o.m.j.c.i.ConnectionHelper.connectSocket(ConnectionHelper.java:137)\n\tat o.m.j.c.i.StandardClient.<init>(StandardClient.java:99)\n\tat o.m.jdbc.Driver.connect(Driver.java:70)\n\tat o.m.jdbc.Driver.connect(Driver.java:101)\n\tat o.m.jdbc.Driver.connect(Driver.java:27)\n\tat c.z.h.u.DriverDataSource.getConnection(DriverDataSource.java:138)\n\tat c.z.h.pool.PoolBase.newConnection(PoolBase.java:364)\n\tat c.z.h.pool.PoolBase.newPoolEntry(PoolBase.java:206)\n\tat c.z.h.p.HikariPool.createPoolEntry(HikariPool.java:476)\n\tat c.z.h.p.HikariPool.checkFailFast(HikariPool.java:561)\n\tat c.z.h.p.HikariPool.<init>(HikariPool.java:115)\n\tat c.z.h.HikariDataSource.getConnection(HikariDataSource.java:112)\n\tat o.h.e.j.c.i.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:181)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)\n\tat o.h.b.r.i.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)\n\tat o.h.s.i.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:272)\n\tat o.h.s.i.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246)\n\tat o.h.s.i.AbstractServiceRegistryImpl.g...\n"}
{"timestamp":"2024-02-26 14:43:45.142","logger":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"ERROR","thread":"restartedMain","message":"Failed to initialize JPA EntityManagerFactory: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]"}
{"timestamp":"2024-02-26 14:43:45.144","logger":"org.springframework.boot.web.embedded.tomcat.TomcatStarter","level":"ERROR","thread":"restartedMain","message":"Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'jwtAuthenticationFilter' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtAuthenticationFilter.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jwtService' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userDetailsServiceImpl' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/domain/build/classes/kotlin/main/kr/co/jsol/domain/userdetails/UserDetailsServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'accountQueryRepository' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/domain/build/classes/kotlin/main/kr/co/jsol/domain/account/infrastructure/query/AccountQueryRepository.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accountRepository' defined in kr.co.jsol.domain.account.infrastructure.repository.AccountRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Cannot create inner bean '(inner bean)#7cdd45af' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#7cdd45af': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]"}
{"timestamp":"2024-02-26 14:43:45.202","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"o.h.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set\n\tat o.h.e.j.d.i.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:100)\n\tat o.h.e.j.d.i.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:54)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:138)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)\n\tat o.h.b.r.i.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)\n\tat o.h.s.i.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:272)\n\t... 149 common frames omitted\nWrapped by: o.h.s.s.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]\n\tat o.h.s.i.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:284)\n\tat o.h.s.i.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246)\n\tat o.h.s.i.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:223)\n\tat o.h.i.f.i.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:175)\n\tat o.h.s.i.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:295)\n\tat o.h.s.i.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:252)\n\tat o.h.s.i.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:223)\n\tat o.h.b.i.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:173)\n\tat o.h.b.m.p.s.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:127)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)\n\tat o.s.o.j.v.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalC...\n"}
{"timestamp":"2024-02-26 15:06:39.412","logger":"com.zaxxer.hikari.pool.HikariPool","level":"ERROR","thread":"restartedMain","message":"HikariPool-1 - Exception during pool initialization.","stack_trace":"j.s.SQLSyntaxErrorException: (conn=49) Unknown database 'integration_mcall'\n\tat o.m.j.e.ExceptionFactory.createException(ExceptionFactory.java:282)\n\tat o.m.j.e.ExceptionFactory.create(ExceptionFactory.java:370)\n\tat o.m.j.c.i.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)\n\tat o.m.j.c.i.StandardClient.<init>(StandardClient.java:185)\n\tat o.m.jdbc.Driver.connect(Driver.java:70)\n\tat o.m.jdbc.Driver.connect(Driver.java:101)\n\tat o.m.jdbc.Driver.connect(Driver.java:27)\n\tat c.z.h.u.DriverDataSource.getConnection(DriverDataSource.java:138)\n\tat c.z.h.pool.PoolBase.newConnection(PoolBase.java:364)\n\tat c.z.h.pool.PoolBase.newPoolEntry(PoolBase.java:206)\n\tat c.z.h.p.HikariPool.createPoolEntry(HikariPool.java:476)\n\tat c.z.h.p.HikariPool.checkFailFast(HikariPool.java:561)\n\tat c.z.h.p.HikariPool.<init>(HikariPool.java:115)\n\tat c.z.h.HikariDataSource.getConnection(HikariDataSource.java:112)\n\tat o.s.b.a.h.H2ConsoleAutoConfiguration.lambda$logDataSources$1(H2ConsoleAutoConfiguration.java:86)\n\tat j.u.s.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)\n\tat java.util.ArrayList.forEach(ArrayList.java:1511)\n\tat j.u.s.SortedOps$RefSortingSink.end(SortedOps.java:395)\n\tat j.u.s.Sink$ChainedReference.end(Sink.java:258)\n\tat j.u.s.Sink$ChainedReference.end(Sink.java:258)\n\tat j.u.s.AbstractPipeline.copyInto(AbstractPipeline.java:510)\n\tat j.u.s.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)\n\tat j.u.s.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)\n\tat j.u.s.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n\tat j.u.s.ReferencePipeline.collect(ReferencePipeline.java:682)\n\tat o.s.b.a.h.H2ConsoleAutoConfiguration.logDataSources(H2ConsoleAutoConfiguration.java:92)\n\tat o.s.b.a.h.H2ConsoleAutoConfiguration.lambda$h2Console$0(H2ConsoleAutoConfiguration.java:68)\n\tat o.s.b.a.h.H2ConsoleAutoConfiguration.withThreadContextClassLoader(H2ConsoleAutoConfiguration.java:77)\n\tat o.s.b.a.h.H2ConsoleAutoConfiguration.h2Console(H2ConsoleAutoConfiguration.java:68)\n\tat j.i.r.NativeMethodAccessorImpl.invoke0(Nativ...\n"}
{"timestamp":"2024-02-26 15:06:40.788","logger":"com.zaxxer.hikari.pool.HikariPool","level":"ERROR","thread":"restartedMain","message":"HikariPool-1 - Exception during pool initialization.","stack_trace":"j.s.SQLSyntaxErrorException: (conn=50) Unknown database 'integration_mcall'\n\tat o.m.j.e.ExceptionFactory.createException(ExceptionFactory.java:282)\n\tat o.m.j.e.ExceptionFactory.create(ExceptionFactory.java:370)\n\tat o.m.j.c.i.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)\n\tat o.m.j.c.i.StandardClient.<init>(StandardClient.java:185)\n\tat o.m.jdbc.Driver.connect(Driver.java:70)\n\tat o.m.jdbc.Driver.connect(Driver.java:101)\n\tat o.m.jdbc.Driver.connect(Driver.java:27)\n\tat c.z.h.u.DriverDataSource.getConnection(DriverDataSource.java:138)\n\tat c.z.h.pool.PoolBase.newConnection(PoolBase.java:364)\n\tat c.z.h.pool.PoolBase.newPoolEntry(PoolBase.java:206)\n\tat c.z.h.p.HikariPool.createPoolEntry(HikariPool.java:476)\n\tat c.z.h.p.HikariPool.checkFailFast(HikariPool.java:561)\n\tat c.z.h.p.HikariPool.<init>(HikariPool.java:115)\n\tat c.z.h.HikariDataSource.getConnection(HikariDataSource.java:112)\n\tat o.h.e.j.c.i.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:181)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)\n\tat o.h.b.r.i.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)\n\tat o.h.s.i.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:272)\n\tat o.h.s.i.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246)\n\tat o.h.s.i.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:223)\n\tat o.h.i.f.i.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:175)\n\tat o.h.s.i.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:295)\n\tat o.h.s.i.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:252)\n\tat o.h.s.i.AbstractServiceRegistryImpl.getSer...\n"}
{"timestamp":"2024-02-26 15:06:40.798","logger":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"ERROR","thread":"restartedMain","message":"Failed to initialize JPA EntityManagerFactory: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]"}
{"timestamp":"2024-02-26 15:06:40.803","logger":"org.springframework.boot.web.embedded.tomcat.TomcatStarter","level":"ERROR","thread":"restartedMain","message":"Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'jwtAuthenticationFilter' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtAuthenticationFilter.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jwtService' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userDetailsServiceImpl' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/domain/build/classes/kotlin/main/kr/co/jsol/domain/userdetails/UserDetailsServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'accountQueryRepository' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/domain/build/classes/kotlin/main/kr/co/jsol/domain/account/infrastructure/query/AccountQueryRepository.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accountRepository' defined in kr.co.jsol.domain.account.infrastructure.repository.AccountRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Cannot create inner bean '(inner bean)#6f6b0a5a' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#6f6b0a5a': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]"}
{"timestamp":"2024-02-26 15:06:40.873","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"o.h.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set\n\tat o.h.e.j.d.i.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:100)\n\tat o.h.e.j.d.i.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:54)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:138)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)\n\tat o.h.b.r.i.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)\n\tat o.h.s.i.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:272)\n\t... 149 common frames omitted\nWrapped by: o.h.s.s.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]\n\tat o.h.s.i.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:284)\n\tat o.h.s.i.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246)\n\tat o.h.s.i.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:223)\n\tat o.h.i.f.i.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:175)\n\tat o.h.s.i.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:295)\n\tat o.h.s.i.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:252)\n\tat o.h.s.i.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:223)\n\tat o.h.b.i.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:173)\n\tat o.h.b.m.p.s.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:127)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)\n\tat o.s.o.j.v.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalC...\n"}
{"timestamp":"2024-02-26 15:08:00.530","logger":"com.zaxxer.hikari.pool.HikariPool","level":"ERROR","thread":"restartedMain","message":"HikariPool-1 - Exception during pool initialization.","stack_trace":"j.n.ConnectException: Connection refused\n\tat sun.nio.ch.Net.pollConnect(Net.java)\n\tat sun.nio.ch.Net.pollConnectNow(Net.java:672)\n\tat s.n.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:547)\n\tat s.n.ch.NioSocketImpl.connect(NioSocketImpl.java:602)\n\tat j.n.SocksSocketImpl.connect(SocksSocketImpl.java:327)\n\tat java.net.Socket.connect(Socket.java:633)\n\tat o.m.j.c.i.ConnectionHelper.connectSocket(ConnectionHelper.java:131)\n\t... 92 common frames omitted\nWrapped by: j.s.SQLNonTransientConnectionException: Socket fail to connect to host:address=(host=localhost)(port=58806)(type=primary). Connection refused\n\tat o.m.j.c.i.ConnectionHelper.connectSocket(ConnectionHelper.java:137)\n\tat o.m.j.c.i.StandardClient.<init>(StandardClient.java:99)\n\tat o.m.jdbc.Driver.connect(Driver.java:70)\n\tat o.m.jdbc.Driver.connect(Driver.java:101)\n\tat o.m.jdbc.Driver.connect(Driver.java:27)\n\tat c.z.h.u.DriverDataSource.getConnection(DriverDataSource.java:138)\n\tat c.z.h.pool.PoolBase.newConnection(PoolBase.java:364)\n\tat c.z.h.pool.PoolBase.newPoolEntry(PoolBase.java:206)\n\tat c.z.h.p.HikariPool.createPoolEntry(HikariPool.java:476)\n\tat c.z.h.p.HikariPool.checkFailFast(HikariPool.java:561)\n\tat c.z.h.p.HikariPool.<init>(HikariPool.java:115)\n\tat c.z.h.HikariDataSource.getConnection(HikariDataSource.java:112)\n\tat o.s.b.a.h.H2ConsoleAutoConfiguration.lambda$logDataSources$1(H2ConsoleAutoConfiguration.java:86)\n\tat j.u.s.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)\n\tat java.util.ArrayList.forEach(ArrayList.java:1511)\n\tat j.u.s.SortedOps$RefSortingSink.end(SortedOps.java:395)\n\tat j.u.s.Sink$ChainedReference.end(Sink.java:258)\n\tat j.u.s.Sink$ChainedReference.end(Sink.java:258)\n\tat j.u.s.AbstractPipeline.copyInto(AbstractPipeline.java:510)\n\tat j.u.s.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)\n\tat j.u.s.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)\n\tat j.u.s.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n\tat j.u.s.ReferencePipeline.collect(ReferencePipeline.java:682)\n\tat o.s.b.a.h.H2ConsoleAutoConfigur...\n"}
{"timestamp":"2024-02-26 15:08:01.912","logger":"com.zaxxer.hikari.pool.HikariPool","level":"ERROR","thread":"restartedMain","message":"HikariPool-1 - Exception during pool initialization.","stack_trace":"j.n.ConnectException: Connection refused\n\tat sun.nio.ch.Net.pollConnect(Net.java)\n\tat sun.nio.ch.Net.pollConnectNow(Net.java:672)\n\tat s.n.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:554)\n\tat s.n.ch.NioSocketImpl.connect(NioSocketImpl.java:602)\n\tat j.n.SocksSocketImpl.connect(SocksSocketImpl.java:327)\n\tat java.net.Socket.connect(Socket.java:633)\n\tat o.m.j.c.i.ConnectionHelper.connectSocket(ConnectionHelper.java:131)\n\t... 166 common frames omitted\nWrapped by: j.s.SQLNonTransientConnectionException: Socket fail to connect to host:address=(host=localhost)(port=58806)(type=primary). Connection refused\n\tat o.m.j.c.i.ConnectionHelper.connectSocket(ConnectionHelper.java:137)\n\tat o.m.j.c.i.StandardClient.<init>(StandardClient.java:99)\n\tat o.m.jdbc.Driver.connect(Driver.java:70)\n\tat o.m.jdbc.Driver.connect(Driver.java:101)\n\tat o.m.jdbc.Driver.connect(Driver.java:27)\n\tat c.z.h.u.DriverDataSource.getConnection(DriverDataSource.java:138)\n\tat c.z.h.pool.PoolBase.newConnection(PoolBase.java:364)\n\tat c.z.h.pool.PoolBase.newPoolEntry(PoolBase.java:206)\n\tat c.z.h.p.HikariPool.createPoolEntry(HikariPool.java:476)\n\tat c.z.h.p.HikariPool.checkFailFast(HikariPool.java:561)\n\tat c.z.h.p.HikariPool.<init>(HikariPool.java:115)\n\tat c.z.h.HikariDataSource.getConnection(HikariDataSource.java:112)\n\tat o.h.e.j.c.i.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:181)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)\n\tat o.h.b.r.i.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)\n\tat o.h.s.i.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:272)\n\tat o.h.s.i.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246)\n\tat o.h.s.i.AbstractServiceRegistryImpl....\n"}
{"timestamp":"2024-02-26 15:08:01.924","logger":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"ERROR","thread":"restartedMain","message":"Failed to initialize JPA EntityManagerFactory: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]"}
{"timestamp":"2024-02-26 15:08:01.929","logger":"org.springframework.boot.web.embedded.tomcat.TomcatStarter","level":"ERROR","thread":"restartedMain","message":"Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'jwtAuthenticationFilter' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtAuthenticationFilter.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jwtService' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userDetailsServiceImpl' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/domain/build/classes/kotlin/main/kr/co/jsol/domain/userdetails/UserDetailsServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'accountQueryRepository' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/domain/build/classes/kotlin/main/kr/co/jsol/domain/account/infrastructure/query/AccountQueryRepository.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accountRepository' defined in kr.co.jsol.domain.account.infrastructure.repository.AccountRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Cannot create inner bean '(inner bean)#7ac0f188' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#7ac0f188': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]"}
{"timestamp":"2024-02-26 15:08:01.999","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"o.h.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set\n\tat o.h.e.j.d.i.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:100)\n\tat o.h.e.j.d.i.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:54)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:138)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)\n\tat o.h.b.r.i.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)\n\tat o.h.s.i.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:272)\n\t... 149 common frames omitted\nWrapped by: o.h.s.s.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]\n\tat o.h.s.i.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:284)\n\tat o.h.s.i.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246)\n\tat o.h.s.i.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:223)\n\tat o.h.i.f.i.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:175)\n\tat o.h.s.i.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:295)\n\tat o.h.s.i.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:252)\n\tat o.h.s.i.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:223)\n\tat o.h.b.i.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:173)\n\tat o.h.b.m.p.s.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:127)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)\n\tat o.s.o.j.v.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalC...\n"}
{"timestamp":"2024-02-26 15:09:39.952","logger":"com.zaxxer.hikari.pool.HikariPool","level":"ERROR","thread":"restartedMain","message":"HikariPool-1 - Exception during pool initialization.","stack_trace":"j.s.SQLSyntaxErrorException: (conn=51) Unknown database 'integration_mcall'\n\tat o.m.j.e.ExceptionFactory.createException(ExceptionFactory.java:282)\n\tat o.m.j.e.ExceptionFactory.create(ExceptionFactory.java:370)\n\tat o.m.j.c.i.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)\n\tat o.m.j.c.i.StandardClient.<init>(StandardClient.java:185)\n\tat o.m.jdbc.Driver.connect(Driver.java:70)\n\tat o.m.jdbc.Driver.connect(Driver.java:101)\n\tat o.m.jdbc.Driver.connect(Driver.java:27)\n\tat c.z.h.u.DriverDataSource.getConnection(DriverDataSource.java:138)\n\tat c.z.h.pool.PoolBase.newConnection(PoolBase.java:364)\n\tat c.z.h.pool.PoolBase.newPoolEntry(PoolBase.java:206)\n\tat c.z.h.p.HikariPool.createPoolEntry(HikariPool.java:476)\n\tat c.z.h.p.HikariPool.checkFailFast(HikariPool.java:561)\n\tat c.z.h.p.HikariPool.<init>(HikariPool.java:115)\n\tat c.z.h.HikariDataSource.getConnection(HikariDataSource.java:112)\n\tat o.s.b.a.h.H2ConsoleAutoConfiguration.lambda$logDataSources$1(H2ConsoleAutoConfiguration.java:86)\n\tat j.u.s.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)\n\tat java.util.ArrayList.forEach(ArrayList.java:1511)\n\tat j.u.s.SortedOps$RefSortingSink.end(SortedOps.java:395)\n\tat j.u.s.Sink$ChainedReference.end(Sink.java:258)\n\tat j.u.s.Sink$ChainedReference.end(Sink.java:258)\n\tat j.u.s.AbstractPipeline.copyInto(AbstractPipeline.java:510)\n\tat j.u.s.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)\n\tat j.u.s.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)\n\tat j.u.s.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n\tat j.u.s.ReferencePipeline.collect(ReferencePipeline.java:682)\n\tat o.s.b.a.h.H2ConsoleAutoConfiguration.logDataSources(H2ConsoleAutoConfiguration.java:92)\n\tat o.s.b.a.h.H2ConsoleAutoConfiguration.lambda$h2Console$0(H2ConsoleAutoConfiguration.java:68)\n\tat o.s.b.a.h.H2ConsoleAutoConfiguration.withThreadContextClassLoader(H2ConsoleAutoConfiguration.java:77)\n\tat o.s.b.a.h.H2ConsoleAutoConfiguration.h2Console(H2ConsoleAutoConfiguration.java:68)\n\tat j.i.r.NativeMethodAccessorImpl.invoke0(Nativ...\n"}
{"timestamp":"2024-02-26 15:09:41.317","logger":"com.zaxxer.hikari.pool.HikariPool","level":"ERROR","thread":"restartedMain","message":"HikariPool-1 - Exception during pool initialization.","stack_trace":"j.s.SQLSyntaxErrorException: (conn=52) Unknown database 'integration_mcall'\n\tat o.m.j.e.ExceptionFactory.createException(ExceptionFactory.java:282)\n\tat o.m.j.e.ExceptionFactory.create(ExceptionFactory.java:370)\n\tat o.m.j.c.i.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)\n\tat o.m.j.c.i.StandardClient.<init>(StandardClient.java:185)\n\tat o.m.jdbc.Driver.connect(Driver.java:70)\n\tat o.m.jdbc.Driver.connect(Driver.java:101)\n\tat o.m.jdbc.Driver.connect(Driver.java:27)\n\tat c.z.h.u.DriverDataSource.getConnection(DriverDataSource.java:138)\n\tat c.z.h.pool.PoolBase.newConnection(PoolBase.java:364)\n\tat c.z.h.pool.PoolBase.newPoolEntry(PoolBase.java:206)\n\tat c.z.h.p.HikariPool.createPoolEntry(HikariPool.java:476)\n\tat c.z.h.p.HikariPool.checkFailFast(HikariPool.java:561)\n\tat c.z.h.p.HikariPool.<init>(HikariPool.java:115)\n\tat c.z.h.HikariDataSource.getConnection(HikariDataSource.java:112)\n\tat o.h.e.j.c.i.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:181)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)\n\tat o.h.b.r.i.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)\n\tat o.h.s.i.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:272)\n\tat o.h.s.i.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246)\n\tat o.h.s.i.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:223)\n\tat o.h.i.f.i.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:175)\n\tat o.h.s.i.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:295)\n\tat o.h.s.i.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:252)\n\tat o.h.s.i.AbstractServiceRegistryImpl.getSer...\n"}
{"timestamp":"2024-02-26 15:09:41.326","logger":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"ERROR","thread":"restartedMain","message":"Failed to initialize JPA EntityManagerFactory: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]"}
{"timestamp":"2024-02-26 15:09:41.332","logger":"org.springframework.boot.web.embedded.tomcat.TomcatStarter","level":"ERROR","thread":"restartedMain","message":"Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'jwtAuthenticationFilter' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtAuthenticationFilter.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jwtService' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userDetailsServiceImpl' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/domain/build/classes/kotlin/main/kr/co/jsol/domain/userdetails/UserDetailsServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'accountQueryRepository' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/domain/build/classes/kotlin/main/kr/co/jsol/domain/account/infrastructure/query/AccountQueryRepository.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accountRepository' defined in kr.co.jsol.domain.account.infrastructure.repository.AccountRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Cannot create inner bean '(inner bean)#48b8761d' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#48b8761d': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]"}
{"timestamp":"2024-02-26 15:09:41.393","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"o.h.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set\n\tat o.h.e.j.d.i.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:100)\n\tat o.h.e.j.d.i.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:54)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:138)\n\tat o.h.e.j.e.i.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)\n\tat o.h.b.r.i.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)\n\tat o.h.s.i.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:272)\n\t... 149 common frames omitted\nWrapped by: o.h.s.s.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]\n\tat o.h.s.i.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:284)\n\tat o.h.s.i.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246)\n\tat o.h.s.i.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:223)\n\tat o.h.i.f.i.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:175)\n\tat o.h.s.i.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:295)\n\tat o.h.s.i.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:252)\n\tat o.h.s.i.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:223)\n\tat o.h.b.i.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:173)\n\tat o.h.b.m.p.s.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:127)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)\n\tat o.s.o.j.v.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalC...\n"}
{"timestamp":"2024-02-26 15:10:36.776","logger":"org.springframework.boot.web.embedded.tomcat.TomcatStarter","level":"ERROR","thread":"restartedMain","message":"Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'jwtAuthenticationFilter' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtAuthenticationFilter.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jwtService' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtService.class]: Unexpected exception during bean creation; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'secret-key' in value \"${secret-key}\""}
{"timestamp":"2024-02-26 15:10:36.835","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"j.l.IllegalArgumentException: Could not resolve placeholder 'secret-key' in value \"${secret-key}\"\n\tat o.s.u.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:180)\n\tat o.s.u.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)\n\tat o.s.c.e.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:239)\n\tat o.s.c.e.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210)\n\tat o.s.c.s.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:191)\n\tat o.s.b.f.s.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:936)\n\tat o.s.b.f.s.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1332)\n\tat o.s.b.f.s.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)\n\tat o.s.b.f.s.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:911)\n\tat o.s.b.f.s.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788)\n\tat o.s.b.f.s.ConstructorResolver.autowireConstructor(ConstructorResolver.java:224)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)\n\t... 70 common frames omitted\nWrapped by: o.s.b.f.BeanCreationException: Error creating bean with name 'jwtService' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtService.class]: Unexpected exception during bean creation; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'secret-key' in value \"${secret-key}\"\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactor...\n"}
{"timestamp":"2024-02-26 15:11:10.611","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"j.l.IllegalArgumentException: Could not resolve placeholder 'media.dir' in value \"${media.dir}\"\n\tat o.s.u.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:180)\n\tat o.s.u.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)\n\tat o.s.c.e.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:239)\n\tat o.s.c.e.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210)\n\tat o.s.c.s.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:191)\n\tat o.s.b.f.s.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:936)\n\tat o.s.b.f.s.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1332)\n\tat o.s.b.f.s.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)\n\tat o.s.b.f.a.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:710)\n\tat o.s.b.f.a.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:693)\n\tat o.s.b.f.a.InjectionMetadata.inject(InjectionMetadata.java:119)\n\tat o.s.b.f.a.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:408)\n\t... 62 common frames omitted\nWrapped by: o.s.b.f.BeanCreationException: Error creating bean with name 'webConfig': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'media.dir' in value \"${media.dir}\"\n\tat o.s.b.f.a.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:414)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:...\n"}
{"timestamp":"2024-02-26 15:20:14.708","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"8ab9c23d7161c0e2e083f25310546485","spanId":"da3127d8c066d72d","message":"illegalArgumentExceptionHandler - message : [http:/172.168.0.1:11001/api/users] is not a valid HTTP URL"}
{"timestamp":"2024-02-26 15:20:44.964","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"8b91debdbadfcab1465989f3d5e2c093","spanId":"4b56d695108ec59f","message":"illegalArgumentExceptionHandler - message : [http:/localhost:11001/api/users] is not a valid HTTP URL"}
{"timestamp":"2024-02-26 15:31:57.583","logger":"org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter","level":"ERROR","thread":"restartedMain","message":"\n\n***************************\nAPPLICATION FAILED TO START\n***************************\n\nDescription:\n\nParameter 0 of constructor in kr.co.jsol.api.controller.AccountController required a bean of type 'kr.co.jsol.domain.account.application.AccountService' that could not be found.\n\n\nAction:\n\nConsider defining a bean of type 'kr.co.jsol.domain.account.application.AccountService' in your configuration.\n"}
{"timestamp":"2024-02-26 15:39:58.765","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","message":"handleMethodArgumentNotValidException - message : 업체 아이디는 1이상의 값이어야 합니다."}
{"timestamp":"2024-02-26 15:40:09.975","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-2","message":"handleMethodArgumentNotValidException - message : 업체 아이디는 1이상의 값이어야 합니다."}
{"timestamp":"2024-02-26 15:40:13.879","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-3","message":"handleMethodArgumentNotValidException - message : 업체 아이디는 1이상의 값이어야 합니다."}
{"timestamp":"2024-02-26 15:41:18.367","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-4","message":"CustomException - message : id로 업체 정보를 찾을 수 없습니다."}
{"timestamp":"2024-02-26 15:41:18.368","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-4","message":"id로 업체 정보를 찾을 수 없습니다."}
{"timestamp":"2024-02-26 15:43:15.211","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-6","message":"CustomException - message : id로 업체 정보를 찾을 수 없습니다."}
{"timestamp":"2024-02-26 15:43:15.213","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-6","message":"id로 업체 정보를 찾을 수 없습니다."}
{"timestamp":"2024-02-26 15:43:17.323","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-7","message":"CustomException - message : id로 업체 정보를 찾을 수 없습니다."}
{"timestamp":"2024-02-26 15:43:17.324","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-7","message":"id로 업체 정보를 찾을 수 없습니다."}
{"timestamp":"2024-02-26 15:44:36.541","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"4ca4c6678535674967ac802798cec1eb","spanId":"91d42fb8feff4e18","message":"CustomException - message : id로 업체 정보를 찾을 수 없습니다."}
{"timestamp":"2024-02-26 15:44:36.542","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"4ca4c6678535674967ac802798cec1eb","spanId":"91d42fb8feff4e18","message":"id로 업체 정보를 찾을 수 없습니다."}
{"timestamp":"2024-02-26 15:45:39.614","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"064ca82dd3c43cdcb743b8e8de4432d9","spanId":"339e6e4d1476a484","message":"CustomException - message : id로 업체 정보를 찾을 수 없습니다."}
{"timestamp":"2024-02-26 15:45:39.615","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"064ca82dd3c43cdcb743b8e8de4432d9","spanId":"339e6e4d1476a484","message":"id로 업체 정보를 찾을 수 없습니다."}
{"timestamp":"2024-02-26 15:49:23.827","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-2","message":"CustomException - message : id로 업체 정보를 찾을 수 없습니다."}
{"timestamp":"2024-02-26 15:49:23.830","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-2","message":"id로 업체 정보를 찾을 수 없습니다."}
{"timestamp":"2024-02-26 15:49:30.374","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-3","message":"CustomException - message : id로 업체 정보를 찾을 수 없습니다."}
{"timestamp":"2024-02-26 15:49:30.374","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-3","message":"id로 업체 정보를 찾을 수 없습니다."}
{"timestamp":"2024-02-26 15:49:30.412","logger":"io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter","level":"ERROR","thread":"OkHttp http://localhost:4317/...","message":"Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317"}
{"timestamp":"2024-02-26 15:58:35.505","logger":"org.springframework.boot.web.embedded.tomcat.TomcatStarter","level":"ERROR","thread":"restartedMain","message":"Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'jwtAuthenticationFilter' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtAuthenticationFilter.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jwtService' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userDetailsServiceImpl' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/domain/build/classes/kotlin/main/kr/co/jsol/domain/userdetails/UserDetailsServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'accountQueryRepository' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/domain/build/classes/kotlin/main/kr/co/jsol/domain/account/infrastructure/query/AccountQueryRepository.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accountRepository' defined in kr.co.jsol.domain.account.infrastructure.repository.AccountRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Cannot create inner bean '(inner bean)#108ab72b' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#108ab72b': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration': Unsatisfied dependency expressed through constructor parameter 4; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'spring.jpa.hibernate-org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties': Could not bind properties to 'HibernateProperties' : prefix=spring.jpa.hibernate, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.jpa.hibernate.naming' to org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties$Naming"}
{"timestamp":"2024-02-26 15:58:35.546","logger":"org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter","level":"ERROR","thread":"restartedMain","message":"\n\n***************************\nAPPLICATION FAILED TO START\n***************************\n\nDescription:\n\nFailed to bind properties under 'spring.jpa.hibernate.naming' to org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties$Naming:\n\n    Reason: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties$Naming]\n\nAction:\n\nUpdate your application's configuration\n"}
{"timestamp":"2024-02-26 16:10:32.958","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"j.l.ClassNotFoundException: kr.co.jsol.domain.account.entity.Account\n\tat j.i.l.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)\n\tat j.i.l.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)\n\tat j.lang.ClassLoader.loadClass(ClassLoader.java:525)\n\tat java.lang.Class.forName0(Class.java)\n\tat java.lang.Class.forName(Class.java:467)\n\tat o.s.b.d.r.c.RestartClassLoader.loadClass(RestartClassLoader.java:145)\n\tat j.lang.ClassLoader.loadClass(ClassLoader.java:525)\n\tat java.lang.Class.forName0(Class.java)\n\tat java.lang.Class.forName(Class.java:467)\n\tat s.r.g.f.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)\n\t... 45 common frames omitted\nWrapped by: j.l.TypeNotPresentException: Type kr.co.jsol.domain.account.entity.Account not present\n\tat s.r.g.f.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)\n\tat s.r.g.v.Reifier.visitClassTypeSignature(Reifier.java:125)\n\tat s.r.g.t.ClassTypeSignature.accept(ClassTypeSignature.java:49)\n\tat s.r.g.v.Reifier.reifyTypeArguments(Reifier.java:68)\n\tat s.r.g.v.Reifier.visitClassTypeSignature(Reifier.java:138)\n\tat s.r.g.t.ClassTypeSignature.accept(ClassTypeSignature.java:49)\n\tat s.r.g.r.ClassRepository.computeSuperInterfaces(ClassRepository.java:117)\n\tat s.r.g.r.ClassRepository.getSuperInterfaces(ClassRepository.java:95)\n\tat java.lang.Class.getGenericInterfaces(Class.java:1211)\n\tat o.s.c.ResolvableType.getInterfaces(ResolvableType.java:507)\n\tat o.s.c.GenericTypeResolver.buildTypeVariableMap(GenericTypeResolver.java:271)\n\tat o.s.c.GenericTypeResolver.getTypeVariableMap(GenericTypeResolver.java:248)\n\tat o.s.d.u.ClassTypeInformation.getTypeVariableMap(ClassTypeInformation.java:120)\n\tat o.s.d.u.ClassTypeInformation.getTypeVariableMap(ClassTypeInformation.java:109)\n\tat o.s.d.u.ClassTypeInformation.<init>(ClassTypeInformation.java:96)\n\tat j.u.c.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330)\n\tat o.s.d.u.ClassTypeInformation.from(ClassTypeInformation.java:73)\n\tat o.s.d.r.c.s.AbstractRepositoryMetadata.<init>(AbstractRepositoryMetadata.java:...\n"}
{"timestamp":"2024-02-26 16:10:35.221","logger":"org.springframework.boot.web.embedded.tomcat.TomcatStarter","level":"ERROR","thread":"restartedMain","message":"Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'jwtAuthenticationFilter' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtAuthenticationFilter.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jwtService' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userDetailsServiceImpl' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/domain/build/classes/kotlin/main/kr/co/jsol/domain/userdetails/UserDetailsServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'accountQueryRepository' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/domain/build/classes/kotlin/main/kr/co/jsol/domain/account/infrastructure/query/AccountQueryRepository.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accountRepository' defined in kr.co.jsol.domain.account.infrastructure.repository.AccountRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Cannot create inner bean '(inner bean)#13ff7bed' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#13ff7bed': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration': Unsatisfied dependency expressed through constructor parameter 4; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'spring.jpa.hibernate-org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties': Could not bind properties to 'HibernateProperties' : prefix=spring.jpa.hibernate, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.jpa.hibernate.naming' to org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties$Naming"}
{"timestamp":"2024-02-26 16:10:35.234","logger":"org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter","level":"ERROR","thread":"restartedMain","message":"\n\n***************************\nAPPLICATION FAILED TO START\n***************************\n\nDescription:\n\nFailed to bind properties under 'spring.jpa.hibernate.naming' to org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties$Naming:\n\n    Reason: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties$Naming]\n\nAction:\n\nUpdate your application's configuration\n"}
{"timestamp":"2024-02-26 16:12:14.288","logger":"org.springframework.boot.web.embedded.tomcat.TomcatStarter","level":"ERROR","thread":"restartedMain","message":"Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'jwtAuthenticationFilter' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtAuthenticationFilter.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jwtService' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userDetailsServiceImpl' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/domain/build/classes/kotlin/main/kr/co/jsol/domain/userdetails/UserDetailsServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'accountQueryRepository' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/domain/build/classes/kotlin/main/kr/co/jsol/domain/account/infrastructure/query/AccountQueryRepository.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accountRepository' defined in kr.co.jsol.domain.account.infrastructure.repository.AccountRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Cannot create inner bean '(inner bean)#1d6b06c4' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#1d6b06c4': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration': Unsatisfied dependency expressed through constructor parameter 4; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'spring.jpa.hibernate-org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties': Could not bind properties to 'HibernateProperties' : prefix=spring.jpa.hibernate, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.jpa.hibernate.naming' to org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties$Naming"}
{"timestamp":"2024-02-26 16:12:14.302","logger":"org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter","level":"ERROR","thread":"restartedMain","message":"\n\n***************************\nAPPLICATION FAILED TO START\n***************************\n\nDescription:\n\nFailed to bind properties under 'spring.jpa.hibernate.naming' to org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties$Naming:\n\n    Reason: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties$Naming]\n\nAction:\n\nUpdate your application's configuration\n"}
{"timestamp":"2024-02-26 16:18:55.097","logger":"org.springframework.boot.web.embedded.tomcat.TomcatStarter","level":"ERROR","thread":"restartedMain","message":"Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'jwtAuthenticationFilter' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtAuthenticationFilter.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jwtService' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userDetailsServiceImpl' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/domain/build/classes/kotlin/main/kr/co/jsol/domain/userdetails/UserDetailsServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'accountQueryRepository' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/domain/build/classes/kotlin/main/kr/co/jsol/domain/account/infrastructure/query/AccountQueryRepository.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accountRepository' defined in kr.co.jsol.domain.account.infrastructure.repository.AccountRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Cannot create inner bean '(inner bean)#91016f2' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#91016f2': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration': Unsatisfied dependency expressed through constructor parameter 4; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'spring.jpa.hibernate-org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties': Could not bind properties to 'HibernateProperties' : prefix=spring.jpa.hibernate, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.jpa.hibernate.naming' to org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties$Naming"}
{"timestamp":"2024-02-26 16:18:55.112","logger":"org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter","level":"ERROR","thread":"restartedMain","message":"\n\n***************************\nAPPLICATION FAILED TO START\n***************************\n\nDescription:\n\nFailed to bind properties under 'spring.jpa.hibernate.naming' to org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties$Naming:\n\n    Reason: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties$Naming]\n\nAction:\n\nUpdate your application's configuration\n"}
{"timestamp":"2024-02-26 16:19:28.493","logger":"org.springframework.boot.web.embedded.tomcat.TomcatStarter","level":"ERROR","thread":"restartedMain","message":"Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'jwtAuthenticationFilter' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtAuthenticationFilter.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jwtService' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userDetailsServiceImpl' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/domain/build/classes/kotlin/main/kr/co/jsol/domain/userdetails/UserDetailsServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'accountQueryRepository' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/domain/build/classes/kotlin/main/kr/co/jsol/domain/account/infrastructure/query/AccountQueryRepository.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accountRepository' defined in kr.co.jsol.domain.account.infrastructure.repository.AccountRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Cannot create inner bean '(inner bean)#7f7cc33c' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#7f7cc33c': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration': Unsatisfied dependency expressed through constructor parameter 4; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'spring.jpa.hibernate-org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties': Could not bind properties to 'HibernateProperties' : prefix=spring.jpa.hibernate, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.jpa.hibernate.naming' to org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties$Naming"}
{"timestamp":"2024-02-26 16:19:28.606","logger":"org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter","level":"ERROR","thread":"restartedMain","message":"\n\n***************************\nAPPLICATION FAILED TO START\n***************************\n\nDescription:\n\nFailed to bind properties under 'spring.jpa.hibernate.naming' to org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties$Naming:\n\n    Reason: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties$Naming]\n\nAction:\n\nUpdate your application's configuration\n"}
{"timestamp":"2024-02-26 16:19:53.384","logger":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"ERROR","thread":"restartedMain","message":"Failed to initialize JPA EntityManagerFactory: Unable to create unique key constraint (managerId) on table shop: database column 'managerId' not found. Make sure that you use the correct column name which depends on the naming strategy in use (it may not be the same as the property name in the entity, especially for relational types)"}
{"timestamp":"2024-02-26 16:19:53.386","logger":"org.springframework.boot.web.embedded.tomcat.TomcatStarter","level":"ERROR","thread":"restartedMain","message":"Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'jwtAuthenticationFilter' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtAuthenticationFilter.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jwtService' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userDetailsServiceImpl' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/domain/build/classes/kotlin/main/kr/co/jsol/domain/userdetails/UserDetailsServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'accountQueryRepository' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/domain/build/classes/kotlin/main/kr/co/jsol/domain/account/infrastructure/query/AccountQueryRepository.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accountRepository' defined in kr.co.jsol.domain.account.infrastructure.repository.AccountRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Cannot create inner bean '(inner bean)#63b03ce4' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#63b03ce4': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: Unable to create unique key constraint (managerId) on table shop: database column 'managerId' not found. Make sure that you use the correct column name which depends on the naming strategy in use (it may not be the same as the property name in the entity, especially for relational types)"}
{"timestamp":"2024-02-26 16:19:53.443","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"o.h.AnnotationException: Unable to create unique key constraint (managerId) on table shop: database column 'managerId' not found. Make sure that you use the correct column name which depends on the naming strategy in use (it may not be the same as the property name in the entity, especially for relational types)\n\tat o.h.b.i.InFlightMetadataCollectorImpl.buildUniqueKeyFromColumnNames(InFlightMetadataCollectorImpl.java:2060)\n\tat o.h.b.i.InFlightMetadataCollectorImpl.buildUniqueKeyFromColumnNames(InFlightMetadataCollectorImpl.java:1921)\n\tat o.h.b.i.InFlightMetadataCollectorImpl.processUniqueConstraintHolders(InFlightMetadataCollectorImpl.java:1909)\n\tat o.h.b.i.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1635)\n\tat o.h.b.m.p.s.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:295)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)\n\tat o.s.o.j.v.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)\n\t... 132 common frames omitted\nWrapped by: o.s.b.f.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframe...\n"}
{"timestamp":"2024-02-26 16:22:38.243","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","message":"Exception - message : 403 : [no body]"}
{"timestamp":"2024-02-26 16:22:38.244","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","message":"403 : [no body]","stack_trace":"o.s.w.c.HttpClientErrorException$Forbidden: 403 : [no body]\n\tat o.s.w.c.HttpClientErrorException.create(HttpClientErrorException.java:109)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)\n\tat o.s.w.c.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)\n\tat o.s.w.c.RestTemplate.handleResponse(RestTemplate.java:825)\n\tat o.s.w.c.RestTemplate.doExecute(RestTemplate.java:783)\n\tat o.s.w.c.RestTemplate.execute(RestTemplate.java:717)\n\tat o.s.w.c.RestTemplate.postForEntity(RestTemplate.java:474)\n\tat k.c.j.d.a.a.AccountService.createAccount(AccountService.kt:78)\n\tat k.c.j.d.a.a.AccountService$$FastClassBySpringCGLIB$$53551004.invoke(<generated>)\n\tat o.s.c.p.MethodProxy.invoke(MethodProxy.java:218)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.t.i.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)\n\tat o.s.t.i.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)\n\tat o.s.t.i.TransactionInterceptor.invoke(TransactionInterceptor.java:119)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.a.f.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)\n\tat k.c.j.d.a.a.AccountService$$EnhancerBySpringCGLIB$$f949de57.createAccount(<generated>)\n\tat k.c.j.a.c.AccountController.createAccount(AccountController.kt:55)\n\tat j.i.r.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)\n\tat j.i.r.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat j.i.r.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat j.l.reflect.Method.invoke(Method.java:568...\n"}
{"timestamp":"2024-02-26 16:24:21.224","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-2","message":"Exception - message : 409 : \"중복된 아이디입니다.\""}
{"timestamp":"2024-02-26 16:24:21.226","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-2","message":"409 : \"중복된 아이디입니다.\"","stack_trace":"o.s.w.c.HttpClientErrorException$Conflict: 409 : \"중복된 아이디입니다.\"\n\tat o.s.w.c.HttpClientErrorException.create(HttpClientErrorException.java:125)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)\n\tat o.s.w.c.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)\n\tat o.s.w.c.RestTemplate.handleResponse(RestTemplate.java:825)\n\tat o.s.w.c.RestTemplate.doExecute(RestTemplate.java:783)\n\tat o.s.w.c.RestTemplate.execute(RestTemplate.java:717)\n\tat o.s.w.c.RestTemplate.postForEntity(RestTemplate.java:474)\n\tat k.c.j.d.a.a.AccountService.createAccount(AccountService.kt:78)\n\tat k.c.j.d.a.a.AccountService$$FastClassBySpringCGLIB$$53551004.invoke(<generated>)\n\tat o.s.c.p.MethodProxy.invoke(MethodProxy.java:218)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.t.i.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)\n\tat o.s.t.i.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)\n\tat o.s.t.i.TransactionInterceptor.invoke(TransactionInterceptor.java:119)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.a.f.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)\n\tat k.c.j.d.a.a.AccountService$$EnhancerBySpringCGLIB$$f949de57.createAccount(<generated>)\n\tat k.c.j.a.c.AccountController.createAccount(AccountController.kt:55)\n\tat j.i.r.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)\n\tat j.i.r.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat j.i.r.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat j.l.reflect.Method.invoke(Method.java:...\n"}
{"timestamp":"2024-02-26 16:26:25.500","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-3","message":"Exception - message : 409 : \"중복된 아이디입니다.\""}
{"timestamp":"2024-02-26 16:26:25.595","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-3","message":"409 : \"중복된 아이디입니다.\"","stack_trace":"o.s.w.c.HttpClientErrorException$Conflict: 409 : \"중복된 아이디입니다.\"\n\tat o.s.w.c.HttpClientErrorException.create(HttpClientErrorException.java:125)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)\n\tat o.s.w.c.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)\n\tat o.s.w.c.RestTemplate.handleResponse(RestTemplate.java:825)\n\tat o.s.w.c.RestTemplate.doExecute(RestTemplate.java:783)\n\tat o.s.w.c.RestTemplate.execute(RestTemplate.java:717)\n\tat o.s.w.c.RestTemplate.postForEntity(RestTemplate.java:474)\n\tat k.c.j.d.a.a.AccountService.createAccount(AccountService.kt:78)\n\tat k.c.j.d.a.a.AccountService$$FastClassBySpringCGLIB$$53551004.invoke(<generated>)\n\tat o.s.c.p.MethodProxy.invoke(MethodProxy.java:218)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.t.i.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)\n\tat o.s.t.i.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)\n\tat o.s.t.i.TransactionInterceptor.invoke(TransactionInterceptor.java:119)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.a.f.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)\n\tat k.c.j.d.a.a.AccountService$$EnhancerBySpringCGLIB$$f949de57.createAccount(<generated>)\n\tat k.c.j.a.c.AccountController.createAccount(AccountController.kt:55)\n\tat j.i.r.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)\n\tat j.i.r.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat j.i.r.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat j.l.reflect.Method.invoke(Method.java:...\n"}
{"timestamp":"2024-02-26 16:29:13.397","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","message":"kotlin.Exception - message : 409 : \"중복된 아이디입니다.\""}
{"timestamp":"2024-02-26 16:29:13.409","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","message":"409 : \"중복된 아이디입니다.\"","stack_trace":"o.s.w.c.HttpClientErrorException$Conflict: 409 : \"중복된 아이디입니다.\"\n\tat o.s.w.c.HttpClientErrorException.create(HttpClientErrorException.java:125)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)\n\tat o.s.w.c.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)\n\tat o.s.w.c.RestTemplate.handleResponse(RestTemplate.java:825)\n\tat o.s.w.c.RestTemplate.doExecute(RestTemplate.java:783)\n\tat o.s.w.c.RestTemplate.execute(RestTemplate.java:717)\n\tat o.s.w.c.RestTemplate.postForEntity(RestTemplate.java:474)\n\tat k.c.j.d.a.a.AccountService.createAccount(AccountService.kt:78)\n\tat k.c.j.d.a.a.AccountService$$FastClassBySpringCGLIB$$53551004.invoke(<generated>)\n\tat o.s.c.p.MethodProxy.invoke(MethodProxy.java:218)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.t.i.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)\n\tat o.s.t.i.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)\n\tat o.s.t.i.TransactionInterceptor.invoke(TransactionInterceptor.java:119)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.a.f.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)\n\tat k.c.j.d.a.a.AccountService$$EnhancerBySpringCGLIB$$f949de57.createAccount(<generated>)\n\tat k.c.j.a.c.AccountController.createAccount(AccountController.kt:55)\n\tat j.i.r.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)\n\tat j.i.r.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat j.i.r.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat j.l.reflect.Method.invoke(Method.java:...\n"}
{"timestamp":"2024-02-26 16:31:21.871","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"753b81ce3e4e6f7a0ab09ed1c1bfb630","spanId":"0319379268fe74ff","message":"CustomException - message : 409 : \"중복된 아이디입니다.\""}
{"timestamp":"2024-02-26 16:31:21.872","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"753b81ce3e4e6f7a0ab09ed1c1bfb630","spanId":"0319379268fe74ff","message":"409 : \"중복된 아이디입니다.\"","stack_trace":"o.s.w.c.HttpClientErrorException$Conflict: 409 : \"중복된 아이디입니다.\"\n\tat o.s.w.c.HttpClientErrorException.create(HttpClientErrorException.java:125)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)\n\tat o.s.w.c.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)\n\tat o.s.w.c.RestTemplate.handleResponse(RestTemplate.java:825)\n\tat o.s.w.c.RestTemplate.doExecute(RestTemplate.java:783)\n\tat o.s.w.c.RestTemplate.execute(RestTemplate.java:717)\n\tat o.s.w.c.RestTemplate.postForEntity(RestTemplate.java:474)\n\tat k.c.j.d.a.a.AccountService.createAccount(Unknown Source:89)\n\tat k.c.j.d.a.a.AccountService$$FastClassBySpringCGLIB$$53551004.invoke(<generated>)\n\tat o.s.c.p.MethodProxy.invoke(MethodProxy.java:218)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.t.i.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)\n\tat o.s.t.i.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)\n\tat o.s.t.i.TransactionInterceptor.invoke(TransactionInterceptor.java:119)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.a.f.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)\n\tat k.c.j.d.a.a.AccountService$$EnhancerBySpringCGLIB$$c9f389f9.createAccount(<generated>)\n\tat k.c.j.a.c.AccountController.createAccount(AccountController.kt:55)\n\tat j.i.r.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)\n\tat j.i.r.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat j.i.r.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat j.l.reflect.Method.invoke(Method.java:568...\n"}
{"timestamp":"2024-02-26 16:31:21.939","logger":"io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter","level":"ERROR","thread":"OkHttp http://localhost:4317/...","message":"Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317"}
{"timestamp":"2024-02-26 16:31:37.218","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","message":"CustomException - message : 409 : \"중복된 아이디입니다.\""}
{"timestamp":"2024-02-26 16:31:37.219","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","message":"409 : \"중복된 아이디입니다.\"","stack_trace":"o.s.w.c.HttpClientErrorException$Conflict: 409 : \"중복된 아이디입니다.\"\n\tat o.s.w.c.HttpClientErrorException.create(HttpClientErrorException.java:125)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)\n\tat o.s.w.c.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)\n\tat o.s.w.c.RestTemplate.handleResponse(RestTemplate.java:825)\n\tat o.s.w.c.RestTemplate.doExecute(RestTemplate.java:783)\n\tat o.s.w.c.RestTemplate.execute(RestTemplate.java:717)\n\tat o.s.w.c.RestTemplate.postForEntity(RestTemplate.java:474)\n\tat k.c.j.d.a.a.AccountService.createAccount(AccountService.kt:89)\n\tat k.c.j.d.a.a.AccountService$$FastClassBySpringCGLIB$$53551004.invoke(<generated>)\n\tat o.s.c.p.MethodProxy.invoke(MethodProxy.java:218)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.t.i.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)\n\tat o.s.t.i.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)\n\tat o.s.t.i.TransactionInterceptor.invoke(TransactionInterceptor.java:119)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.a.f.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)\n\tat k.c.j.d.a.a.AccountService$$EnhancerBySpringCGLIB$$c9f389f9.createAccount(<generated>)\n\tat k.c.j.a.c.AccountController.createAccount(AccountController.kt:55)\n\tat j.i.r.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)\n\tat j.i.r.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat j.i.r.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat j.l.reflect.Method.invoke(Method.java:...\n"}
{"timestamp":"2024-02-26 16:34:48.950","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"4ccbcd937038282636277fb1b6061b24","spanId":"8659a9b3e1202995","message":"CustomException - message :  \"중복된 아이디입니다.\""}
{"timestamp":"2024-02-26 16:34:48.950","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"4ccbcd937038282636277fb1b6061b24","spanId":"8659a9b3e1202995","message":" \"중복된 아이디입니다.\"","stack_trace":"o.s.w.c.HttpClientErrorException$Conflict: 409 : \"중복된 아이디입니다.\"\n\tat o.s.w.c.HttpClientErrorException.create(HttpClientErrorException.java:125)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)\n\tat o.s.w.c.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)\n\tat o.s.w.c.RestTemplate.handleResponse(RestTemplate.java:825)\n\tat o.s.w.c.RestTemplate.doExecute(RestTemplate.java:783)\n\tat o.s.w.c.RestTemplate.execute(RestTemplate.java:717)\n\tat o.s.w.c.RestTemplate.postForEntity(RestTemplate.java:474)\n\tat k.c.j.d.a.a.AccountService.createAccount(AccountService.kt:105)\n\tat k.c.j.d.a.a.AccountService$$FastClassBySpringCGLIB$$53551004.invoke(<generated>)\n\tat o.s.c.p.MethodProxy.invoke(MethodProxy.java:218)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.t.i.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)\n\tat o.s.t.i.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)\n\tat o.s.t.i.TransactionInterceptor.invoke(TransactionInterceptor.java:119)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.a.f.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)\n\tat k.c.j.d.a.a.AccountService$$EnhancerBySpringCGLIB$$5892eaed.createAccount(<generated>)\n\tat k.c.j.a.c.AccountController.createAccount(AccountController.kt:55)\n\tat j.i.r.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)\n\tat j.i.r.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat j.i.r.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat j.l.reflect.Method.invoke(Method.java...\n"}
{"timestamp":"2024-02-26 16:35:32.690","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"b3fe6cd6ddbcf74b4aec36aa025b3bd3","spanId":"14bbcc4fe694b91f","message":"CustomException - message :  중복된 아이디입니다."}
{"timestamp":"2024-02-26 16:35:32.691","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"b3fe6cd6ddbcf74b4aec36aa025b3bd3","spanId":"14bbcc4fe694b91f","message":" 중복된 아이디입니다.","stack_trace":"o.s.w.c.HttpClientErrorException$Conflict: 409 : \"중복된 아이디입니다.\"\n\tat o.s.w.c.HttpClientErrorException.create(HttpClientErrorException.java:125)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)\n\tat o.s.w.c.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)\n\tat o.s.w.c.RestTemplate.handleResponse(RestTemplate.java:825)\n\tat o.s.w.c.RestTemplate.doExecute(RestTemplate.java:783)\n\tat o.s.w.c.RestTemplate.execute(RestTemplate.java:717)\n\tat o.s.w.c.RestTemplate.postForEntity(RestTemplate.java:474)\n\tat k.c.j.d.a.a.AccountService.createAccount(AccountService.kt:106)\n\tat k.c.j.d.a.a.AccountService$$FastClassBySpringCGLIB$$53551004.invoke(<generated>)\n\tat o.s.c.p.MethodProxy.invoke(MethodProxy.java:218)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.t.i.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)\n\tat o.s.t.i.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)\n\tat o.s.t.i.TransactionInterceptor.invoke(TransactionInterceptor.java:119)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.a.f.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)\n\tat k.c.j.d.a.a.AccountService$$EnhancerBySpringCGLIB$$1b672c74.createAccount(<generated>)\n\tat k.c.j.a.c.AccountController.createAccount(AccountController.kt:55)\n\tat j.i.r.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)\n\tat j.i.r.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat j.i.r.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat j.l.reflect.Method.invoke(Method.java...\n"}
{"timestamp":"2024-02-26 16:36:50.122","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"216e571bc9bc75022bfaa9fecf1af819","spanId":"afc160f282c17784","message":"CustomException - message : 중복된 아이디입니다."}
{"timestamp":"2024-02-26 16:36:50.124","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"216e571bc9bc75022bfaa9fecf1af819","spanId":"afc160f282c17784","message":"중복된 아이디입니다.","stack_trace":"o.s.w.c.HttpClientErrorException$Conflict: 409 : \"중복된 아이디입니다.\"\n\tat o.s.w.c.HttpClientErrorException.create(HttpClientErrorException.java:125)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)\n\tat o.s.w.c.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)\n\tat o.s.w.c.RestTemplate.handleResponse(RestTemplate.java:825)\n\tat o.s.w.c.RestTemplate.doExecute(RestTemplate.java:783)\n\tat o.s.w.c.RestTemplate.execute(RestTemplate.java:717)\n\tat o.s.w.c.RestTemplate.postForEntity(RestTemplate.java:474)\n\tat k.c.j.d.a.a.AccountService.createAccount(AccountService.kt:107)\n\tat k.c.j.d.a.a.AccountService$$FastClassBySpringCGLIB$$53551004.invoke(<generated>)\n\tat o.s.c.p.MethodProxy.invoke(MethodProxy.java:218)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.t.i.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)\n\tat o.s.t.i.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)\n\tat o.s.t.i.TransactionInterceptor.invoke(TransactionInterceptor.java:119)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.a.f.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)\n\tat k.c.j.d.a.a.AccountService$$EnhancerBySpringCGLIB$$d53220d0.createAccount(<generated>)\n\tat k.c.j.a.c.AccountController.createAccount(AccountController.kt:55)\n\tat j.i.r.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)\n\tat j.i.r.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat j.i.r.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat j.l.reflect.Method.invoke(Method.java...\n"}
{"timestamp":"2024-02-26 16:38:08.180","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-3","traceId":"bbc6ffb0d4ad5cd957d410c8e058e501","spanId":"ac8b10dc3cc2a0a9","message":"CustomException - message : 중복된 아이디입니다."}
{"timestamp":"2024-02-26 16:38:08.182","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-3","traceId":"bbc6ffb0d4ad5cd957d410c8e058e501","spanId":"ac8b10dc3cc2a0a9","message":"중복된 아이디입니다.","stack_trace":"o.s.w.c.HttpClientErrorException$Conflict: 409 : \"중복된 아이디입니다.\"\n\tat o.s.w.c.HttpClientErrorException.create(HttpClientErrorException.java:125)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)\n\tat o.s.w.c.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)\n\tat o.s.w.c.RestTemplate.handleResponse(RestTemplate.java:825)\n\tat o.s.w.c.RestTemplate.doExecute(RestTemplate.java:783)\n\tat o.s.w.c.RestTemplate.execute(RestTemplate.java:717)\n\tat o.s.w.c.RestTemplate.postForEntity(RestTemplate.java:474)\n\tat k.c.j.d.a.a.AccountService.createAccount(AccountService.kt:107)\n\tat k.c.j.d.a.a.AccountService$$FastClassBySpringCGLIB$$53551004.invoke(<generated>)\n\tat o.s.c.p.MethodProxy.invoke(MethodProxy.java:218)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.t.i.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)\n\tat o.s.t.i.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)\n\tat o.s.t.i.TransactionInterceptor.invoke(TransactionInterceptor.java:119)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.a.f.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)\n\tat k.c.j.d.a.a.AccountService$$EnhancerBySpringCGLIB$$d53220d0.createAccount(<generated>)\n\tat k.c.j.a.c.AccountController.createAccount(AccountController.kt:55)\n\tat j.i.r.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)\n\tat j.i.r.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat j.i.r.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat j.l.reflect.Method.invoke(Method.java...\n"}
{"timestamp":"2024-02-26 16:38:21.391","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-5","traceId":"4df4368f17aaa8114c5461266f049789","spanId":"e384df0a5a223ca8","message":"kotlin.Exception - message : No accessor to set property @org.hibernate.annotations.Comment(\"\\uc0dd\\uc131\\uc77c\\uc2dc\") @javax.persistence.Column(nullable=true, unique=false, precision=0, name=\"created_at\", length=255, scale=0, updatable=true, columnDefinition=\"\", table=\"\", insertable=true) @org.springframework.data.annotation.CreatedDate()private final java.time.LocalDateTime kr.co.jsol.common.domain.BaseEntity.createdAt"}
{"timestamp":"2024-02-26 16:38:21.392","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-5","traceId":"4df4368f17aaa8114c5461266f049789","spanId":"e384df0a5a223ca8","message":"No accessor to set property @org.hibernate.annotations.Comment(\"\\uc0dd\\uc131\\uc77c\\uc2dc\") @javax.persistence.Column(nullable=true, unique=false, precision=0, name=\"created_at\", length=255, scale=0, updatable=true, columnDefinition=\"\", table=\"\", insertable=true) @org.springframework.data.annotation.CreatedDate()private final java.time.LocalDateTime kr.co.jsol.common.domain.BaseEntity.createdAt","stack_trace":"j.l.UnsupportedOperationException: No accessor to set property @org.hibernate.annotations.Comment(\"\\uc0dd\\uc131\\uc77c\\uc2dc\") @javax.persistence.Column(nullable=true, unique=false, precision=0, name=\"created_at\", length=255, scale=0, updatable=true, columnDefinition=\"\", table=\"\", insertable=true) @org.springframework.data.annotation.CreatedDate()private final java.time.LocalDateTime kr.co.jsol.common.domain.BaseEntity.createdAt\n\tat k.c.j.d.a.e.Account_Accessor_9q9f54.setProperty(Unknown Source)\n\tat o.s.d.m.m.InstantiationAwarePropertyAccessor.setProperty(InstantiationAwarePropertyAccessor.java:105)\n\tat o.s.d.m.m.SimplePersistentPropertyPathAccessor.setProperty(SimplePersistentPropertyPathAccessor.java:128)\n\tat o.s.d.m.m.SimplePersistentPropertyPathAccessor.setProperty(SimplePersistentPropertyPathAccessor.java:172)\n\tat o.s.d.a.MappingAuditableBeanWrapperFactory$MappingMetadataAuditableBeanWrapper.lambda$setDateProperty$1(MappingAuditableBeanWrapperFactory.java:271)\n\tat java.lang.Iterable.forEach(Iterable.java:75)\n\tat o.s.d.a.MappingAuditableBeanWrapperFactory$MappingMetadataAuditableBeanWrapper.setDateProperty(MappingAuditableBeanWrapperFactory.java:267)\n\tat o.s.d.a.MappingAuditableBeanWrapperFactory$MappingMetadataAuditableBeanWrapper.setCreatedDate(MappingAuditableBeanWrapperFactory.java:213)\n\tat java.util.Optional.ifPresent(Optional.java:178)\n\tat o.s.d.a.AuditingHandlerSupport.touchDate(AuditingHandlerSupport.java:192)\n\tat o.s.d.a.AuditingHandlerSupport.lambda$touch$0(AuditingHandlerSupport.java:137)\n\tat java.util.Optional.map(Optional.java:260)\n\tat o.s.d.a.AuditingHandlerSupport.touch(AuditingHandlerSupport.java:134)\n\tat o.s.d.a.AuditingHandlerSupport.markCreated(AuditingHandlerSupport.java:114)\n\tat o.s.d.a.AuditingHandler.markCreated(AuditingHandler.java:92)\n\tat o.s.d.j.d.s.AuditingEntityListener.touchForCreate(AuditingEntityListener.java:92)\n\tat j.i.r.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)\n\tat j.i.r.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat j.i.r.Deleg...\n"}
{"timestamp":"2024-02-26 16:39:46.902","logger":"org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter","level":"ERROR","thread":"restartedMain","message":"\n\n***************************\nAPPLICATION FAILED TO START\n***************************\n\nDescription:\n\nWeb server failed to start. Port 11402 was already in use.\n\nAction:\n\nIdentify and stop the process that's listening on port 11402 or configure this application to listen on another port.\n"}
{"timestamp":"2024-02-26 16:40:22.963","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"10ff8c1ab8f2af8e3de0fd01aa6aff43","spanId":"9f7cee6cb743b57b","message":"CustomException - message : 중복된 아이디입니다."}
{"timestamp":"2024-02-26 16:40:22.964","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"10ff8c1ab8f2af8e3de0fd01aa6aff43","spanId":"9f7cee6cb743b57b","message":"중복된 아이디입니다.","stack_trace":"o.s.w.c.HttpClientErrorException$Conflict: 409 : \"중복된 아이디입니다.\"\n\tat o.s.w.c.HttpClientErrorException.create(HttpClientErrorException.java:125)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)\n\tat o.s.w.c.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)\n\tat o.s.w.c.RestTemplate.handleResponse(RestTemplate.java:825)\n\tat o.s.w.c.RestTemplate.doExecute(RestTemplate.java:783)\n\tat o.s.w.c.RestTemplate.execute(RestTemplate.java:717)\n\tat o.s.w.c.RestTemplate.postForEntity(RestTemplate.java:474)\n\tat k.c.j.d.a.a.AccountService.createAccount(AccountService.kt:107)\n\tat k.c.j.d.a.a.AccountService$$FastClassBySpringCGLIB$$53551004.invoke(<generated>)\n\tat o.s.c.p.MethodProxy.invoke(MethodProxy.java:218)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.t.i.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)\n\tat o.s.t.i.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)\n\tat o.s.t.i.TransactionInterceptor.invoke(TransactionInterceptor.java:119)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.a.f.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)\n\tat k.c.j.d.a.a.AccountService$$EnhancerBySpringCGLIB$$e7d43e9d.createAccount(<generated>)\n\tat k.c.j.a.c.AccountController.createAccount(AccountController.kt:55)\n\tat j.i.r.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)\n\tat j.i.r.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat j.i.r.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat j.l.reflect.Method.invoke(Method.java...\n"}
{"timestamp":"2024-02-26 17:07:12.863","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"ff5b041e62025d05b764e767dd7c1bf6","spanId":"d6ef4b1e6a56c121","message":"CustomException - message : 중복된 아이디입니다."}
{"timestamp":"2024-02-26 17:07:12.865","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"ff5b041e62025d05b764e767dd7c1bf6","spanId":"d6ef4b1e6a56c121","message":"중복된 아이디입니다.","stack_trace":"o.s.w.c.HttpClientErrorException$Conflict: 409 : \"중복된 아이디입니다.\"\n\tat o.s.w.c.HttpClientErrorException.create(HttpClientErrorException.java:125)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)\n\tat o.s.w.c.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)\n\tat o.s.w.c.RestTemplate.handleResponse(RestTemplate.java:825)\n\tat o.s.w.c.RestTemplate.doExecute(RestTemplate.java:783)\n\tat o.s.w.c.RestTemplate.execute(RestTemplate.java:717)\n\tat o.s.w.c.RestTemplate.postForEntity(RestTemplate.java:474)\n\tat k.c.j.d.a.a.AccountService.createAccount(AccountService.kt:88)\n\tat k.c.j.d.a.a.AccountService$$FastClassBySpringCGLIB$$53551004.invoke(<generated>)\n\tat o.s.c.p.MethodProxy.invoke(MethodProxy.java:218)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.t.i.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)\n\tat o.s.t.i.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)\n\tat o.s.t.i.TransactionInterceptor.invoke(TransactionInterceptor.java:119)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.a.f.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)\n\tat k.c.j.d.a.a.AccountService$$EnhancerBySpringCGLIB$$e617754d.createAccount(<generated>)\n\tat k.c.j.a.c.AccountController.createAccount(AccountController.kt:56)\n\tat j.i.r.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)\n\tat j.i.r.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat j.i.r.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat j.l.reflect.Method.invoke(Method.java:...\n"}
{"timestamp":"2024-02-26 17:08:28.636","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"1eb15fe8e9acdbd0433225605348d052","spanId":"8499a10e8aab4753","message":"CustomException - message : 중복된 아이디입니다."}
{"timestamp":"2024-02-26 17:08:28.639","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"1eb15fe8e9acdbd0433225605348d052","spanId":"8499a10e8aab4753","message":"중복된 아이디입니다.","stack_trace":"o.s.w.c.HttpClientErrorException$Conflict: 409 : \"중복된 아이디입니다.\"\n\tat o.s.w.c.HttpClientErrorException.create(HttpClientErrorException.java:125)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)\n\tat o.s.w.c.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)\n\tat o.s.w.c.RestTemplate.handleResponse(RestTemplate.java:825)\n\tat o.s.w.c.RestTemplate.doExecute(RestTemplate.java:783)\n\tat o.s.w.c.RestTemplate.execute(RestTemplate.java:717)\n\tat o.s.w.c.RestTemplate.postForEntity(RestTemplate.java:474)\n\tat k.c.j.d.a.a.AccountService.createAccount(AccountService.kt:90)\n\tat k.c.j.d.a.a.AccountService$$FastClassBySpringCGLIB$$53551004.invoke(<generated>)\n\tat o.s.c.p.MethodProxy.invoke(MethodProxy.java:218)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.t.i.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)\n\tat o.s.t.i.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)\n\tat o.s.t.i.TransactionInterceptor.invoke(TransactionInterceptor.java:119)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.a.f.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)\n\tat k.c.j.d.a.a.AccountService$$EnhancerBySpringCGLIB$$f9e3a493.createAccount(<generated>)\n\tat k.c.j.a.c.AccountController.createAccount(AccountController.kt:56)\n\tat j.i.r.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)\n\tat j.i.r.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat j.i.r.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat j.l.reflect.Method.invoke(Method.java:...\n"}
{"timestamp":"2024-02-26 17:08:42.495","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-3","traceId":"73cb784d56c09959320c07dfb938467b","spanId":"d751c60870567144","message":"CustomException - message : 서버 에러 발생, 담당 개발자에게 연락해주세요."}
{"timestamp":"2024-02-26 17:08:42.496","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-3","traceId":"73cb784d56c09959320c07dfb938467b","spanId":"d751c60870567144","message":"서버 에러 발생, 담당 개발자에게 연락해주세요."}
{"timestamp":"2024-02-26 17:09:04.270","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-4","traceId":"cf8c354ed94f541d0c65b00d92519cfe","spanId":"53818446716e8802","message":"CustomException - message : 서버 에러 발생, 담당 개발자에게 연락해주세요."}
{"timestamp":"2024-02-26 17:09:04.271","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-4","traceId":"cf8c354ed94f541d0c65b00d92519cfe","spanId":"53818446716e8802","message":"서버 에러 발생, 담당 개발자에게 연락해주세요."}
{"timestamp":"2024-02-26 17:09:04.346","logger":"io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter","level":"ERROR","thread":"OkHttp http://localhost:4317/...","message":"Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317"}
{"timestamp":"2024-02-26 17:10:48.113","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-5","traceId":"7828d2a82355293d042348303099ebe3","spanId":"66cd11ba1969f888","message":"CustomException - message : 서버 에러 발생, 담당 개발자에게 연락해주세요."}
{"timestamp":"2024-02-26 17:10:48.116","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-5","traceId":"7828d2a82355293d042348303099ebe3","spanId":"66cd11ba1969f888","message":"서버 에러 발생, 담당 개발자에게 연락해주세요."}
{"timestamp":"2024-02-26 17:10:48.125","logger":"io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter","level":"ERROR","thread":"OkHttp http://localhost:4317/...","message":"Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317"}
{"timestamp":"2024-02-26 17:11:32.935","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-3","traceId":"08f3b34fd24d7021aa197a3264e5b7b3","spanId":"847f3563161aea00","message":"CustomException - message : 중복된 아이디입니다."}
{"timestamp":"2024-02-26 17:11:32.936","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-3","traceId":"08f3b34fd24d7021aa197a3264e5b7b3","spanId":"847f3563161aea00","message":"중복된 아이디입니다.","stack_trace":"o.s.w.c.HttpClientErrorException$Conflict: 409 : \"중복된 아이디입니다.\"\n\tat o.s.w.c.HttpClientErrorException.create(HttpClientErrorException.java:125)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)\n\tat o.s.w.c.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)\n\tat o.s.w.c.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)\n\tat o.s.w.c.RestTemplate.handleResponse(RestTemplate.java:825)\n\tat o.s.w.c.RestTemplate.doExecute(RestTemplate.java:783)\n\tat o.s.w.c.RestTemplate.execute(RestTemplate.java:717)\n\tat o.s.w.c.RestTemplate.postForEntity(RestTemplate.java:474)\n\tat k.c.j.d.a.a.AccountService.createAccount(AccountService.kt:89)\n\tat k.c.j.d.a.a.AccountService$$FastClassBySpringCGLIB$$53551004.invoke(<generated>)\n\tat o.s.c.p.MethodProxy.invoke(MethodProxy.java:218)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.t.i.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)\n\tat o.s.t.i.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)\n\tat o.s.t.i.TransactionInterceptor.invoke(TransactionInterceptor.java:119)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)\n\tat o.s.a.f.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)\n\tat k.c.j.d.a.a.AccountService$$EnhancerBySpringCGLIB$$e958a1e.createAccount(<generated>)\n\tat k.c.j.a.c.AccountController.createAccount(AccountController.kt:56)\n\tat j.i.r.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)\n\tat j.i.r.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat j.i.r.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat j.l.reflect.Method.invoke(Method.java:5...\n"}
{"timestamp":"2024-02-26 17:39:24.509","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-8","traceId":"3184efd1aa8f6f18e601204037e6c48a","spanId":"10adaf8f82877f91","message":"CustomException - message : id로 사용자 정보를 찾을 수 없습니다."}
{"timestamp":"2024-02-26 17:39:24.510","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-8","traceId":"3184efd1aa8f6f18e601204037e6c48a","spanId":"10adaf8f82877f91","message":"id로 사용자 정보를 찾을 수 없습니다."}
{"timestamp":"2024-02-26 17:39:35.418","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"52ce1f8a55a9d709b39ddbdd29401bc0","spanId":"b36b2a62c172d59a","message":"invalidDataAccessApiUsageException - message : No enum constant kr.co.jsol.domain.account.entity.enums.Role.role_user; nested exception is java.lang.IllegalArgumentException: No enum constant kr.co.jsol.domain.account.entity.enums.Role.role_user"}
{"timestamp":"2024-02-26 17:39:51.189","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-10","traceId":"fddc32af762f29e76d9bc9c3d2c5ac30","spanId":"61e90d82ec87edfc","message":"invalidDataAccessApiUsageException - message : No enum constant kr.co.jsol.domain.account.entity.enums.Role.JSOL; nested exception is java.lang.IllegalArgumentException: No enum constant kr.co.jsol.domain.account.entity.enums.Role.JSOL"}
{"timestamp":"2024-02-26 17:59:42.932","logger":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"ERROR","thread":"restartedMain","message":"Failed to initialize JPA EntityManagerFactory: @OneToOne or @ManyToOne on kr.co.jsol.domain.companysubsidy.entity.CompanySubsidy.shop references an unknown entity: kr.co.jsol.domain.shop.entity.Shop"}
{"timestamp":"2024-02-26 17:59:42.934","logger":"org.springframework.boot.web.embedded.tomcat.TomcatStarter","level":"ERROR","thread":"restartedMain","message":"Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'jwtAuthenticationFilter' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtAuthenticationFilter.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jwtService' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/jwt/JwtService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userDetailsServiceImpl' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/domain/build/classes/kotlin/main/kr/co/jsol/domain/userdetails/UserDetailsServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'accountQueryRepository' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/domain/build/classes/kotlin/main/kr/co/jsol/domain/account/infrastructure/query/AccountQueryRepository.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accountRepository' defined in kr.co.jsol.domain.account.infrastructure.repository.AccountRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Cannot create inner bean '(inner bean)#cce5cc7' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#cce5cc7': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on kr.co.jsol.domain.companysubsidy.entity.CompanySubsidy.shop references an unknown entity: kr.co.jsol.domain.shop.entity.Shop"}
{"timestamp":"2024-02-26 17:59:43.024","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"o.h.AnnotationException: @OneToOne or @ManyToOne on kr.co.jsol.domain.companysubsidy.entity.CompanySubsidy.shop references an unknown entity: kr.co.jsol.domain.shop.entity.Shop\n\tat o.h.c.ToOneFkSecondPass.doSecondPass(ToOneFkSecondPass.java:100)\n\tat o.h.b.i.InFlightMetadataCollectorImpl.processEndOfQueue(InFlightMetadataCollectorImpl.java:1750)\n\tat o.h.b.i.InFlightMetadataCollectorImpl.processFkSecondPassesInOrder(InFlightMetadataCollectorImpl.java:1694)\n\tat o.h.b.i.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1623)\n\tat o.h.b.m.p.s.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:295)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)\n\tat o.s.o.j.v.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)\n\t... 132 common frames omitted\nWrapped by: o.s.b.f.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on kr.co.jsol.do...\n"}
