{"timestamp":"2024-02-21 14:06:56.306","logger":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"ERROR","thread":"restartedMain","message":"Failed to initialize JPA EntityManagerFactory: @org.hibernate.annotations.Table references an unknown table:  color"}
{"timestamp":"2024-02-21 14:06:56.366","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"o.h.AnnotationException: @org.hibernate.annotations.Table references an unknown table:  color\n\tat o.h.c.a.EntityBinder.processComplementaryTableDefinitions(EntityBinder.java:1266)\n\tat o.h.c.AnnotationBinder.bindClass(AnnotationBinder.java:825)\n\tat o.h.b.m.s.i.a.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:225)\n\tat o.h.b.m.p.s.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:239)\n\tat o.h.b.m.p.s.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:282)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)\n\tat o.s.o.j.v.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)\n\t... 21 common frames omitted\nWrapped by: o.s.b.f.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @org.hibernate.annotations.Table references an unknown table:  color\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeB...\n"}
{"timestamp":"2024-02-21 14:08:02.560","logger":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"ERROR","thread":"restartedMain","message":"Failed to initialize JPA EntityManagerFactory: @org.hibernate.annotations.Table references an unknown table:  color"}
{"timestamp":"2024-02-21 14:08:02.620","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"o.h.AnnotationException: @org.hibernate.annotations.Table references an unknown table:  color\n\tat o.h.c.a.EntityBinder.processComplementaryTableDefinitions(EntityBinder.java:1266)\n\tat o.h.c.AnnotationBinder.bindClass(AnnotationBinder.java:825)\n\tat o.h.b.m.s.i.a.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:225)\n\tat o.h.b.m.p.s.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:239)\n\tat o.h.b.m.p.s.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:282)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)\n\tat o.s.o.j.v.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)\n\t... 21 common frames omitted\nWrapped by: o.s.b.f.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @org.hibernate.annotations.Table references an unknown table:  color\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeB...\n"}
{"timestamp":"2024-02-21 14:08:42.735","logger":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"ERROR","thread":"restartedMain","message":"Failed to initialize JPA EntityManagerFactory: @org.hibernate.annotations.Table references an unknown table:  color"}
{"timestamp":"2024-02-21 14:08:42.797","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"o.h.AnnotationException: @org.hibernate.annotations.Table references an unknown table:  color\n\tat o.h.c.a.EntityBinder.processComplementaryTableDefinitions(EntityBinder.java:1266)\n\tat o.h.c.AnnotationBinder.bindClass(AnnotationBinder.java:825)\n\tat o.h.b.m.s.i.a.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:225)\n\tat o.h.b.m.p.s.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:239)\n\tat o.h.b.m.p.s.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:282)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)\n\tat o.s.o.j.v.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)\n\t... 21 common frames omitted\nWrapped by: o.s.b.f.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @org.hibernate.annotations.Table references an unknown table:  color\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeB...\n"}
{"timestamp":"2024-02-21 14:09:33.942","logger":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"ERROR","thread":"restartedMain","message":"Failed to initialize JPA EntityManagerFactory: @org.hibernate.annotations.Table references an unknown table:  Color"}
{"timestamp":"2024-02-21 14:09:34.002","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"o.h.AnnotationException: @org.hibernate.annotations.Table references an unknown table:  Color\n\tat o.h.c.a.EntityBinder.processComplementaryTableDefinitions(EntityBinder.java:1266)\n\tat o.h.c.AnnotationBinder.bindClass(AnnotationBinder.java:825)\n\tat o.h.b.m.s.i.a.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:225)\n\tat o.h.b.m.p.s.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:239)\n\tat o.h.b.m.p.s.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:282)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)\n\tat o.s.o.j.v.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)\n\t... 21 common frames omitted\nWrapped by: o.s.b.f.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @org.hibernate.annotations.Table references an unknown table:  Color\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeB...\n"}
{"timestamp":"2024-02-21 14:11:39.189","logger":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"ERROR","thread":"restartedMain","message":"Failed to initialize JPA EntityManagerFactory: @org.hibernate.annotations.Table references an unknown table: master_option"}
{"timestamp":"2024-02-21 14:11:39.254","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"o.h.AnnotationException: @org.hibernate.annotations.Table references an unknown table: master_option\n\tat o.h.c.a.EntityBinder.processComplementaryTableDefinitions(EntityBinder.java:1266)\n\tat o.h.c.AnnotationBinder.bindClass(AnnotationBinder.java:825)\n\tat o.h.b.m.s.i.a.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:225)\n\tat o.h.b.m.p.s.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:239)\n\tat o.h.b.m.p.s.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:282)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)\n\tat o.s.o.j.v.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)\n\t... 21 common frames omitted\nWrapped by: o.s.b.f.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @org.hibernate.annotations.Table references an unknown table: master_option\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFacto...\n"}
{"timestamp":"2024-02-21 14:12:27.394","logger":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"ERROR","thread":"restartedMain","message":"Failed to initialize JPA EntityManagerFactory: @org.hibernate.annotations.Table references an unknown table: user"}
{"timestamp":"2024-02-21 14:12:27.459","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"o.h.AnnotationException: @org.hibernate.annotations.Table references an unknown table: user\n\tat o.h.c.a.EntityBinder.processComplementaryTableDefinitions(EntityBinder.java:1266)\n\tat o.h.c.AnnotationBinder.bindClass(AnnotationBinder.java:825)\n\tat o.h.b.m.s.i.a.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:225)\n\tat o.h.b.m.p.s.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:239)\n\tat o.h.b.m.p.s.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:282)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)\n\tat o.s.o.j.v.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)\n\t... 21 common frames omitted\nWrapped by: o.s.b.f.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @org.hibernate.annotations.Table references an unknown table: user\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeBean(...\n"}
{"timestamp":"2024-02-21 14:14:01.357","logger":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"ERROR","thread":"restartedMain","message":"Failed to initialize JPA EntityManagerFactory: @org.hibernate.annotations.Table references an unknown table:  color"}
{"timestamp":"2024-02-21 14:14:01.421","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"o.h.AnnotationException: @org.hibernate.annotations.Table references an unknown table:  color\n\tat o.h.c.a.EntityBinder.processComplementaryTableDefinitions(EntityBinder.java:1266)\n\tat o.h.c.AnnotationBinder.bindClass(AnnotationBinder.java:825)\n\tat o.h.b.m.s.i.a.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:225)\n\tat o.h.b.m.p.s.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:239)\n\tat o.h.b.m.p.s.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:282)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)\n\tat o.s.o.j.v.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)\n\t... 21 common frames omitted\nWrapped by: o.s.b.f.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @org.hibernate.annotations.Table references an unknown table:  color\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeB...\n"}
{"timestamp":"2024-02-21 14:14:11.577","logger":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"ERROR","thread":"restartedMain","message":"Failed to initialize JPA EntityManagerFactory: @org.hibernate.annotations.Table references an unknown table:  color"}
{"timestamp":"2024-02-21 14:14:11.640","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"o.h.AnnotationException: @org.hibernate.annotations.Table references an unknown table:  color\n\tat o.h.c.a.EntityBinder.processComplementaryTableDefinitions(EntityBinder.java:1266)\n\tat o.h.c.AnnotationBinder.bindClass(AnnotationBinder.java:825)\n\tat o.h.b.m.s.i.a.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:225)\n\tat o.h.b.m.p.s.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:239)\n\tat o.h.b.m.p.s.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:282)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)\n\tat o.s.o.j.v.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)\n\t... 21 common frames omitted\nWrapped by: o.s.b.f.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @org.hibernate.annotations.Table references an unknown table:  color\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeB...\n"}
{"timestamp":"2024-02-21 14:14:37.810","logger":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"ERROR","thread":"restartedMain","message":"Failed to initialize JPA EntityManagerFactory: @org.hibernate.annotations.Table references an unknown table:  color"}
{"timestamp":"2024-02-21 14:14:37.871","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"o.h.AnnotationException: @org.hibernate.annotations.Table references an unknown table:  color\n\tat o.h.c.a.EntityBinder.processComplementaryTableDefinitions(EntityBinder.java:1266)\n\tat o.h.c.AnnotationBinder.bindClass(AnnotationBinder.java:825)\n\tat o.h.b.m.s.i.a.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:225)\n\tat o.h.b.m.p.s.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:239)\n\tat o.h.b.m.p.s.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:282)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)\n\tat o.s.o.j.v.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)\n\t... 21 common frames omitted\nWrapped by: o.s.b.f.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @org.hibernate.annotations.Table references an unknown table:  color\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeB...\n"}
{"timestamp":"2024-02-21 14:16:04.190","logger":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"ERROR","thread":"restartedMain","message":"Failed to initialize JPA EntityManagerFactory: @org.hibernate.annotations.Table references an unknown table:  color"}
{"timestamp":"2024-02-21 14:16:04.254","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"o.h.AnnotationException: @org.hibernate.annotations.Table references an unknown table:  color\n\tat o.h.c.a.EntityBinder.processComplementaryTableDefinitions(EntityBinder.java:1266)\n\tat o.h.c.AnnotationBinder.bindClass(AnnotationBinder.java:825)\n\tat o.h.b.m.s.i.a.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:225)\n\tat o.h.b.m.p.s.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:239)\n\tat o.h.b.m.p.s.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:282)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)\n\tat o.s.o.j.v.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)\n\t... 21 common frames omitted\nWrapped by: o.s.b.f.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @org.hibernate.annotations.Table references an unknown table:  color\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeB...\n"}
{"timestamp":"2024-02-21 14:50:28.387","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"j.l.NullPointerException: Parameter specified as non-null is null: method kr.co.jsol.common.config.db.db.MultiSchemaPhysicalNamingStrategy.toPhysicalCatalogName, parameter name\n\tat k.c.j.c.c.d.d.MultiSchemaPhysicalNamingStrategy.toPhysicalCatalogName(MultiSchemaPhysicalNamingStrategy.kt)\n\tat o.h.b.m.r.Database.setImplicitNamespaceName(Database.java:59)\n\tat o.h.b.m.r.Database.<init>(Database.java:51)\n\tat o.h.b.m.r.Database.<init>(Database.java:42)\n\tat o.h.b.i.InFlightMetadataCollectorImpl.getDatabase(InFlightMetadataCollectorImpl.java:223)\n\tat o.h.b.i.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:184)\n\tat o.h.b.m.p.s.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:127)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)\n\tat o.s.o.j.v.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)\n\t... 21 common frames omitted\nWrapped by: o.s.b.f.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is java...\n"}
{"timestamp":"2024-02-21 14:58:03.192","logger":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"ERROR","thread":"restartedMain","message":"Failed to initialize JPA EntityManagerFactory: @org.hibernate.annotations.Table references an unknown table: account"}
{"timestamp":"2024-02-21 14:58:03.259","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"o.h.AnnotationException: @org.hibernate.annotations.Table references an unknown table: account\n\tat o.h.c.a.EntityBinder.processComplementaryTableDefinitions(EntityBinder.java:1266)\n\tat o.h.c.AnnotationBinder.bindClass(AnnotationBinder.java:825)\n\tat o.h.b.m.s.i.a.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:225)\n\tat o.h.b.m.p.s.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:239)\n\tat o.h.b.m.p.s.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:282)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)\n\tat o.s.o.j.v.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)\n\t... 21 common frames omitted\nWrapped by: o.s.b.f.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @org.hibernate.annotations.Table references an unknown table: account\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializ...\n"}
{"timestamp":"2024-02-21 14:58:39.332","logger":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"ERROR","thread":"restartedMain","message":"Failed to initialize JPA EntityManagerFactory: @org.hibernate.annotations.Table references an unknown table: company_subsidy"}
{"timestamp":"2024-02-21 14:58:39.398","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"o.h.AnnotationException: @org.hibernate.annotations.Table references an unknown table: company_subsidy\n\tat o.h.c.a.EntityBinder.processComplementaryTableDefinitions(EntityBinder.java:1266)\n\tat o.h.c.AnnotationBinder.bindClass(AnnotationBinder.java:825)\n\tat o.h.b.m.s.i.a.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:225)\n\tat o.h.b.m.p.s.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:239)\n\tat o.h.b.m.p.s.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:282)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)\n\tat o.s.o.j.v.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)\n\t... 21 common frames omitted\nWrapped by: o.s.b.f.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @org.hibernate.annotations.Table references an unknown table: company_subsidy\n\tat o.s.b.f.s.AbstractAutowireCapableBeanF...\n"}
{"timestamp":"2024-02-21 14:59:06.329","logger":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"ERROR","thread":"restartedMain","message":"Failed to initialize JPA EntityManagerFactory: @org.hibernate.annotations.Table references an unknown table: device"}
{"timestamp":"2024-02-21 14:59:06.392","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"o.h.AnnotationException: @org.hibernate.annotations.Table references an unknown table: device\n\tat o.h.c.a.EntityBinder.processComplementaryTableDefinitions(EntityBinder.java:1266)\n\tat o.h.c.AnnotationBinder.bindClass(AnnotationBinder.java:825)\n\tat o.h.b.m.s.i.a.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:225)\n\tat o.h.b.m.p.s.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:239)\n\tat o.h.b.m.p.s.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:282)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)\n\tat o.s.o.j.v.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)\n\t... 21 common frames omitted\nWrapped by: o.s.b.f.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @org.hibernate.annotations.Table references an unknown table: device\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeB...\n"}
{"timestamp":"2024-02-21 15:19:16.132","logger":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"ERROR","thread":"restartedMain","message":"Failed to initialize JPA EntityManagerFactory: @org.hibernate.annotations.Table references an unknown table: shop_depot"}
{"timestamp":"2024-02-21 15:19:16.193","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"o.h.AnnotationException: @org.hibernate.annotations.Table references an unknown table: shop_depot\n\tat o.h.c.a.EntityBinder.processComplementaryTableDefinitions(EntityBinder.java:1266)\n\tat o.h.c.AnnotationBinder.bindClass(AnnotationBinder.java:825)\n\tat o.h.b.m.s.i.a.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:225)\n\tat o.h.b.m.p.s.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:239)\n\tat o.h.b.m.p.s.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:282)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)\n\tat o.h.j.b.i.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)\n\tat o.s.o.j.v.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)\n\tat o.s.o.j.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)\n\tat o.s.o.j.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)\n\t... 21 common frames omitted\nWrapped by: o.s.b.f.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @org.hibernate.annotations.Table references an unknown table: shop_depot\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.ini...\n"}
{"timestamp":"2024-02-21 15:41:47.681","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"j.l.NullPointerException: Cannot throw exception because \"null\" is null\n\tat k.c.j.c.c.SwaggerConfig.<init>(SwaggerConfig.kt)\n\tat k.c.j.c.c.SwaggerConfig$$EnhancerBySpringCGLIB$$6dc752c7.<init>(<generated>)\n\tat j.i.r.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java)\n\tat j.i.r.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)\n\tat j.i.r.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n\tat j.l.r.Constructor.newInstanceWithCaller(Constructor.java:499)\n\tat j.l.r.Constructor.newInstance(Constructor.java:480)\n\tat o.s.beans.BeanUtils.instantiateClass(BeanUtils.java:213)\n\t... 24 common frames omitted\nWrapped by: o.s.b.BeanInstantiationException: Failed to instantiate [kr.co.jsol.common.config.SwaggerConfig$$EnhancerBySpringCGLIB$$6dc752c7]: Constructor threw exception; nested exception is java.lang.NullPointerException: Cannot throw exception because \"null\" is null\n\tat o.s.beans.BeanUtils.instantiateClass(BeanUtils.java:226)\n\tat o.s.b.f.s.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1326)\n\t... 22 common frames omitted\nWrapped by: o.s.b.f.BeanCreationException: Error creating bean with name 'swaggerConfig' defined in file [/Users/leeseongbok/workspace/Github/IDM-BACKEND/common/build/classes/kotlin/main/kr/co/jsol/common/config/SwaggerConfig.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [kr.co.jsol.common.config.SwaggerConfig$$EnhancerBySpringCGLIB$$6dc752c7]: Constructor threw exception; nested exception is java.lang.NullPointerException: Cannot throw exception because \"null\" is null\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1334)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:12...\n"}
{"timestamp":"2024-02-21 15:43:22.340","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]","level":"ERROR","thread":"http-nio-11402-exec-6","traceId":"65298f51539147293403d70c5cba01f8","spanId":"385bc2dc6f8dd09c","message":"Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException: Parameter specified as non-null is null: method kr.co.jsol.api.controller.AccountController.createBuilding, parameter userDetails] with root cause","stack_trace":"j.l.NullPointerException: Parameter specified as non-null is null: method kr.co.jsol.api.controller.AccountController.createBuilding, parameter userDetails\n\tat k.c.j.a.c.AccountController.createBuilding(AccountController.kt)\n\tat j.i.r.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)\n\tat j.i.r.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat j.i.r.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat j.l.reflect.Method.invoke(Method.java:568)\n\tat o.s.w.m.s.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)\n\tat o.s.w.m.s.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)\n\tat o.s.w.s.m.m.a.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)\n\tat o.s.w.s.m.m.a.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)\n\tat o.s.w.s.m.m.a.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)\n\tat o.s.w.s.m.m.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)\n\tat o.s.w.s.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)\n\tat o.s.w.s.DispatcherServlet.doService(DispatcherServlet.java:965)\n\tat o.s.w.s.FrameworkServlet.processRequest(FrameworkServlet.java:1006)\n\tat o.s.w.s.FrameworkServlet.doPost(FrameworkServlet.java:909)\n\tat j.s.http.HttpServlet.service(HttpServlet.java:555)\n\tat o.s.w.s.FrameworkServlet.service(FrameworkServlet.java:883)\n\tat j.s.http.HttpServlet.service(HttpServlet.java:623)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)\n\tat o.a.c.c.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)\n\tat o.a.t.w.s.WsFilter.doFilter(WsFilter.java:51)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat o.a.c.c.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:337)\n\tat o.s.s.w.a.i.FilterSecurityInterceptor.invoke(FilterSecurityInt...\n"}
{"timestamp":"2024-02-21 15:46:19.717","logger":"kr.co.jsol.common.exception.ApiExceptionHandler","level":"ERROR","thread":"http-nio-11402-exec-3","traceId":"596645306fe79a68526c80a5444688c3","spanId":"a22ff7ab2992d3f8","message":"NullPointerException - message : Parameter specified as non-null is null: method kr.co.jsol.api.controller.AccountController.createBuilding, parameter userDetails"}
{"timestamp":"2024-02-21 15:51:18.409","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"j.l.ClassNotFoundException: kr.co.jsol.common.exception.storage.StorageException\n\tat j.i.l.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)\n\tat j.i.l.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)\n\tat j.lang.ClassLoader.loadClass(ClassLoader.java:525)\n\tat java.lang.Class.forName0(Class.java)\n\tat java.lang.Class.forName(Class.java:467)\n\tat o.s.b.d.r.c.RestartClassLoader.loadClass(RestartClassLoader.java:145)\n\tat j.lang.ClassLoader.loadClass(ClassLoader.java:525)\n\t... 29 common frames omitted\nWrapped by: j.l.NoClassDefFoundError: kr/co/jsol/common/exception/storage/StorageException\n\tat java.lang.Class.getDeclaredMethods0(Class.java)\n\tat java.lang.Class.privateGetDeclaredMethods(Class.java:3402)\n\tat java.lang.Class.getDeclaredMethods(Class.java:2504)\n\tat o.s.u.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:467)\n\t... 25 common frames omitted\nWrapped by: j.l.IllegalStateException: Failed to introspect Class [kr.co.jsol.common.exception.ApiExceptionHandler] from ClassLoader [org.springframework.boot.devtools.restart.classloader.RestartClassLoader@68ded970]\n\tat o.s.u.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:485)\n\tat o.s.u.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:321)\n\tat o.s.b.f.a.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:276)\n\t... 23 common frames omitted\nWrapped by: o.s.b.f.BeanCreationException: Error creating bean with name 'apiExceptionHandler': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [kr.co.jsol.common.exception.ApiExceptionHandler] from ClassLoader [org.springframework.boot.devtools.restart.classloader.RestartClassLoader@68ded970]\n\tat o.s.b.f.a.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:298)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1302)\n\tat o.s.b.f.s.Ab...\n"}
{"timestamp":"2024-02-21 15:55:20.871","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"2485e0970833f52db23b345ce4b22163","spanId":"e73fc7c60dbf5105","message":"NullPointerException - message : Parameter specified as non-null is null: method kr.co.jsol.api.controller.AccountController.createBuilding, parameter userDetails"}
{"timestamp":"2024-02-21 15:55:59.826","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"8e5a3ea4bb3c4c431a9853ddf7f7e493","spanId":"151845207a8cd1bd","message":"illegalArgumentExceptionHandler - message : Failed to evaluate expression 'JSOL'"}
{"timestamp":"2024-02-21 15:56:31.501","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"39f6403584449362cbca7a93da3beb2b","spanId":"b39bf87af2e7c7ac","message":"illegalArgumentExceptionHandler - message : Failed to evaluate expression 'ROLE_JSOL'"}
{"timestamp":"2024-02-21 15:56:59.174","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"2c5928e6b81b68972c0a7758a1d26714","spanId":"0c635118c531e933","message":"illegalArgumentExceptionHandler - message : Failed to evaluate expression ''ROLE_JSOL''"}
{"timestamp":"2024-02-21 15:58:07.365","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"e1bbe98b3c534382bd45eea2669e827a","spanId":"f845908564ac1ac7","message":"Spring Security - AccessDeniedException - message : 접근이 거부되었습니다."}
{"timestamp":"2024-02-21 15:58:10.589","logger":"kr.co.jsol.common.exception.ApiExceptionHandler$Companion","level":"ERROR","thread":"http-nio-11402-exec-2","traceId":"f95fa60afec54979c214d3d744c3170e","spanId":"5796ea8ac842ad0e","message":"Spring Security - AccessDeniedException - message : 접근이 거부되었습니다."}
{"timestamp":"2024-02-21 15:59:26.464","logger":"io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter","level":"ERROR","thread":"OkHttp http://localhost:4317/...","message":"Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317"}
{"timestamp":"2024-02-21 16:21:45.503","logger":"org.springframework.boot.SpringApplication","level":"ERROR","thread":"restartedMain","message":"Application run failed","stack_trace":"j.l.IllegalStateException: Ambiguous mapping. Cannot map 'accountController' method \nkr.co.jsol.api.controller.AccountController#createBuilding(UserDetailsImpl)\nto {POST [/api/v1/account]}: There is already 'accountController' bean method\nkr.co.jsol.api.controller.AccountController#cr() mapped.\n\tat o.s.w.s.h.AbstractHandlerMethodMapping$MappingRegistry.validateMethodMapping(AbstractHandlerMethodMapping.java:669)\n\tat o.s.w.s.h.AbstractHandlerMethodMapping$MappingRegistry.register(AbstractHandlerMethodMapping.java:635)\n\tat o.s.w.s.h.AbstractHandlerMethodMapping.registerHandlerMethod(AbstractHandlerMethodMapping.java:332)\n\tat o.s.w.s.m.m.a.RequestMappingHandlerMapping.registerHandlerMethod(RequestMappingHandlerMapping.java:420)\n\tat o.s.w.s.m.m.a.RequestMappingHandlerMapping.registerHandlerMethod(RequestMappingHandlerMapping.java:76)\n\tat o.s.w.s.h.AbstractHandlerMethodMapping.lambda$detectHandlerMethods$2(AbstractHandlerMethodMapping.java:299)\n\tat j.util.LinkedHashMap.forEach(LinkedHashMap.java:721)\n\tat o.s.w.s.h.AbstractHandlerMethodMapping.detectHandlerMethods(AbstractHandlerMethodMapping.java:297)\n\tat o.s.w.s.h.AbstractHandlerMethodMapping.processCandidateBean(AbstractHandlerMethodMapping.java:266)\n\tat o.s.w.s.h.AbstractHandlerMethodMapping.initHandlerMethods(AbstractHandlerMethodMapping.java:225)\n\tat o.s.w.s.h.AbstractHandlerMethodMapping.afterPropertiesSet(AbstractHandlerMethodMapping.java:213)\n\tat o.s.w.s.m.m.a.RequestMappingHandlerMapping.afterPropertiesSet(RequestMappingHandlerMapping.java:205)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)\n\tat o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)\n\t... 21 common frames omitted\nWrapped by: o.s.b.f.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init met...\n"}
{"timestamp":"2024-02-21 16:24:52.633","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]","level":"ERROR","thread":"http-nio-11402-exec-5","traceId":"064ae3541c4c7857bf185b4f4be6fc39","spanId":"448cb7c74c502115","message":"Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception","stack_trace":"j.l.IllegalArgumentException: 계정 정보를 찾을 수 없습니다.\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:20)\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:20)\n\tat java.util.Optional.orElseThrow(Optional.java:403)\n\tat k.c.j.d.a.i.q.AccountQueryRepository.getById(AccountQueryRepository.kt:20)\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:14)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.h.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)\n\tat o.s.s.w.h.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.r.a.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.s.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)\n\tat ...\n"}
{"timestamp":"2024-02-21 16:24:52.650","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]","level":"ERROR","thread":"http-nio-11402-exec-5","traceId":"064ae3541c4c7857bf185b4f4be6fc39","spanId":"448cb7c74c502115","message":"Servlet.service() for servlet [dispatcherServlet] threw exception","stack_trace":"j.l.IllegalArgumentException: 계정 정보를 찾을 수 없습니다.\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:20)\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:20)\n\tat java.util.Optional.orElseThrow(Optional.java:403)\n\tat k.c.j.d.a.i.q.AccountQueryRepository.getById(AccountQueryRepository.kt:20)\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:14)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)\n\tat o.s.s.w.FilterChainProxy.doFilter(FilterChainProxy.java:186)\n\tat o.s.w.f.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)\n\tat o.s.w.f.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat o.a.c.c.ApplicationFilterChain.doFilter(Appl...\n"}
{"timestamp":"2024-02-21 16:24:52.651","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost]","level":"ERROR","thread":"http-nio-11402-exec-5","traceId":"064ae3541c4c7857bf185b4f4be6fc39","spanId":"448cb7c74c502115","message":"Exception Processing ErrorPage[errorCode=0, location=/error]","stack_trace":"j.l.IllegalArgumentException: 계정 정보를 찾을 수 없습니다.\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:20)\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:20)\n\tat java.util.Optional.orElseThrow(Optional.java:403)\n\tat k.c.j.d.a.i.q.AccountQueryRepository.getById(AccountQueryRepository.kt:20)\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:14)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)\n\tat o.s.s.w.FilterChainProxy.doFilter(FilterChainProxy.java:186)\n\tat o.s.w.f.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)\n\tat o.s.w.f.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat o.a.c.c.ApplicationFilterChain.doFilter(Appl...\n"}
{"timestamp":"2024-02-21 16:26:09.571","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"b7c75999588b22cd9cdb472c3e3ee9df","spanId":"19af789ed0b7515e","message":"Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception","stack_trace":"k.c.j.c.e.GeneralClientException$BadRequestException: 계정 정보를 찾을 수 없습니다.\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat java.util.Optional.orElseThrow(Optional.java:403)\n\tat k.c.j.d.a.i.q.AccountQueryRepository.getById(AccountQueryRepository.kt:21)\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:14)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.h.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)\n\tat o.s.s.w.h.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.r.a.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.s.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterC...\n"}
{"timestamp":"2024-02-21 16:26:09.587","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"b7c75999588b22cd9cdb472c3e3ee9df","spanId":"19af789ed0b7515e","message":"Servlet.service() for servlet [dispatcherServlet] threw exception","stack_trace":"k.c.j.c.e.GeneralClientException$BadRequestException: 계정 정보를 찾을 수 없습니다.\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat java.util.Optional.orElseThrow(Optional.java:403)\n\tat k.c.j.d.a.i.q.AccountQueryRepository.getById(AccountQueryRepository.kt:21)\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:14)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)\n\tat o.s.s.w.FilterChainProxy.doFilter(FilterChainProxy.java:186)\n\tat o.s.w.f.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)\n\tat o.s.w.f.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat o.a.c.c.ApplicationF...\n"}
{"timestamp":"2024-02-21 16:26:09.589","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost]","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"b7c75999588b22cd9cdb472c3e3ee9df","spanId":"19af789ed0b7515e","message":"Exception Processing ErrorPage[errorCode=0, location=/error]","stack_trace":"k.c.j.c.e.GeneralClientException$BadRequestException: 계정 정보를 찾을 수 없습니다.\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat java.util.Optional.orElseThrow(Optional.java:403)\n\tat k.c.j.d.a.i.q.AccountQueryRepository.getById(AccountQueryRepository.kt:21)\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:14)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)\n\tat o.s.s.w.FilterChainProxy.doFilter(FilterChainProxy.java:186)\n\tat o.s.w.f.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)\n\tat o.s.w.f.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat o.a.c.c.ApplicationF...\n"}
{"timestamp":"2024-02-21 16:26:17.859","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]","level":"ERROR","thread":"http-nio-11402-exec-7","traceId":"88ead5ffa7863942e2a6b4961fa7920f","spanId":"8200fa730bad4847","message":"Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception","stack_trace":"k.c.j.c.e.GeneralClientException$BadRequestException: 계정 정보를 찾을 수 없습니다.\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat java.util.Optional.orElseThrow(Optional.java:403)\n\tat k.c.j.d.a.i.q.AccountQueryRepository.getById(AccountQueryRepository.kt:21)\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:14)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.h.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)\n\tat o.s.s.w.h.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.r.a.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.s.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterC...\n"}
{"timestamp":"2024-02-21 16:26:17.872","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]","level":"ERROR","thread":"http-nio-11402-exec-7","traceId":"88ead5ffa7863942e2a6b4961fa7920f","spanId":"8200fa730bad4847","message":"Servlet.service() for servlet [dispatcherServlet] threw exception","stack_trace":"k.c.j.c.e.GeneralClientException$BadRequestException: 계정 정보를 찾을 수 없습니다.\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat java.util.Optional.orElseThrow(Optional.java:403)\n\tat k.c.j.d.a.i.q.AccountQueryRepository.getById(AccountQueryRepository.kt:21)\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:14)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)\n\tat o.s.s.w.FilterChainProxy.doFilter(FilterChainProxy.java:186)\n\tat o.s.w.f.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)\n\tat o.s.w.f.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat o.a.c.c.ApplicationF...\n"}
{"timestamp":"2024-02-21 16:26:17.874","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost]","level":"ERROR","thread":"http-nio-11402-exec-7","traceId":"88ead5ffa7863942e2a6b4961fa7920f","spanId":"8200fa730bad4847","message":"Exception Processing ErrorPage[errorCode=0, location=/error]","stack_trace":"k.c.j.c.e.GeneralClientException$BadRequestException: 계정 정보를 찾을 수 없습니다.\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat java.util.Optional.orElseThrow(Optional.java:403)\n\tat k.c.j.d.a.i.q.AccountQueryRepository.getById(AccountQueryRepository.kt:21)\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:14)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)\n\tat o.s.s.w.FilterChainProxy.doFilter(FilterChainProxy.java:186)\n\tat o.s.w.f.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)\n\tat o.s.w.f.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat o.a.c.c.ApplicationF...\n"}
{"timestamp":"2024-02-21 16:29:41.878","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"daf7c8810bac45658acf4ca90b2a94bc","spanId":"2b4032f69657e624","message":"Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception","stack_trace":"k.c.j.c.e.GeneralClientException$BadRequestException: 계정 정보를 찾을 수 없습니다.\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat java.util.Optional.orElseThrow(Optional.java:403)\n\tat k.c.j.d.a.i.q.AccountQueryRepository.getById(AccountQueryRepository.kt:21)\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:14)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.h.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)\n\tat o.s.s.w.h.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.r.a.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.s.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterC...\n"}
{"timestamp":"2024-02-21 16:29:41.890","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"daf7c8810bac45658acf4ca90b2a94bc","spanId":"2b4032f69657e624","message":"Servlet.service() for servlet [dispatcherServlet] threw exception","stack_trace":"k.c.j.c.e.GeneralClientException$BadRequestException: 계정 정보를 찾을 수 없습니다.\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat java.util.Optional.orElseThrow(Optional.java:403)\n\tat k.c.j.d.a.i.q.AccountQueryRepository.getById(AccountQueryRepository.kt:21)\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:14)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)\n\tat o.s.s.w.FilterChainProxy.doFilter(FilterChainProxy.java:186)\n\tat o.s.w.f.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)\n\tat o.s.w.f.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat o.a.c.c.ApplicationF...\n"}
{"timestamp":"2024-02-21 16:29:41.891","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost]","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"daf7c8810bac45658acf4ca90b2a94bc","spanId":"2b4032f69657e624","message":"Exception Processing ErrorPage[errorCode=0, location=/error]","stack_trace":"k.c.j.c.e.GeneralClientException$BadRequestException: 계정 정보를 찾을 수 없습니다.\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat java.util.Optional.orElseThrow(Optional.java:403)\n\tat k.c.j.d.a.i.q.AccountQueryRepository.getById(AccountQueryRepository.kt:21)\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:14)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)\n\tat o.s.s.w.FilterChainProxy.doFilter(FilterChainProxy.java:186)\n\tat o.s.w.f.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)\n\tat o.s.w.f.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat o.a.c.c.ApplicationF...\n"}
{"timestamp":"2024-02-21 16:31:46.621","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"1cfdac2822f334e429e44b638f6e4caf","spanId":"9b2e16d32790dbbb","message":"Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception","stack_trace":"k.c.j.c.e.GeneralClientException$BadRequestException: 계정 정보를 찾을 수 없습니다.\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat java.util.Optional.orElseThrow(Optional.java:403)\n\tat k.c.j.d.a.i.q.AccountQueryRepository.getById(AccountQueryRepository.kt:21)\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:14)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.h.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)\n\tat o.s.s.w.h.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.r.a.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.s.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterC...\n"}
{"timestamp":"2024-02-21 16:31:46.635","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"1cfdac2822f334e429e44b638f6e4caf","spanId":"9b2e16d32790dbbb","message":"Servlet.service() for servlet [dispatcherServlet] threw exception","stack_trace":"k.c.j.c.e.GeneralClientException$BadRequestException: 계정 정보를 찾을 수 없습니다.\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat java.util.Optional.orElseThrow(Optional.java:403)\n\tat k.c.j.d.a.i.q.AccountQueryRepository.getById(AccountQueryRepository.kt:21)\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:14)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)\n\tat o.s.s.w.FilterChainProxy.doFilter(FilterChainProxy.java:186)\n\tat o.s.w.f.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)\n\tat o.s.w.f.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat o.a.c.c.ApplicationF...\n"}
{"timestamp":"2024-02-21 16:31:46.637","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost]","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"1cfdac2822f334e429e44b638f6e4caf","spanId":"9b2e16d32790dbbb","message":"Exception Processing ErrorPage[errorCode=0, location=/error]","stack_trace":"k.c.j.c.e.GeneralClientException$BadRequestException: 계정 정보를 찾을 수 없습니다.\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat java.util.Optional.orElseThrow(Optional.java:403)\n\tat k.c.j.d.a.i.q.AccountQueryRepository.getById(AccountQueryRepository.kt:21)\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:14)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)\n\tat o.s.s.w.FilterChainProxy.doFilter(FilterChainProxy.java:186)\n\tat o.s.w.f.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)\n\tat o.s.w.f.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat o.a.c.c.ApplicationF...\n"}
{"timestamp":"2024-02-21 16:31:53.701","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]","level":"ERROR","thread":"http-nio-11402-exec-2","traceId":"9b2e32d501f806c80b922105728d62ea","spanId":"7f4476f7118de972","message":"Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception","stack_trace":"k.c.j.c.e.GeneralClientException$BadRequestException: 계정 정보를 찾을 수 없습니다.\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat java.util.Optional.orElseThrow(Optional.java:403)\n\tat k.c.j.d.a.i.q.AccountQueryRepository.getById(AccountQueryRepository.kt:21)\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:14)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.h.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)\n\tat o.s.s.w.h.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.r.a.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.s.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterC...\n"}
{"timestamp":"2024-02-21 16:31:53.721","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]","level":"ERROR","thread":"http-nio-11402-exec-2","traceId":"9b2e32d501f806c80b922105728d62ea","spanId":"7f4476f7118de972","message":"Servlet.service() for servlet [dispatcherServlet] threw exception","stack_trace":"k.c.j.c.e.GeneralClientException$BadRequestException: 계정 정보를 찾을 수 없습니다.\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat java.util.Optional.orElseThrow(Optional.java:403)\n\tat k.c.j.d.a.i.q.AccountQueryRepository.getById(AccountQueryRepository.kt:21)\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:14)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)\n\tat o.s.s.w.FilterChainProxy.doFilter(FilterChainProxy.java:186)\n\tat o.s.w.f.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)\n\tat o.s.w.f.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat o.a.c.c.ApplicationF...\n"}
{"timestamp":"2024-02-21 16:31:53.723","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost]","level":"ERROR","thread":"http-nio-11402-exec-2","traceId":"9b2e32d501f806c80b922105728d62ea","spanId":"7f4476f7118de972","message":"Exception Processing ErrorPage[errorCode=0, location=/error]","stack_trace":"k.c.j.c.e.GeneralClientException$BadRequestException: 계정 정보를 찾을 수 없습니다.\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat k.c.j.d.a.i.q.AccountQueryRepository$getById$1.get(AccountQueryRepository.kt:21)\n\tat java.util.Optional.orElseThrow(Optional.java:403)\n\tat k.c.j.d.a.i.q.AccountQueryRepository.getById(AccountQueryRepository.kt:21)\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:14)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)\n\tat o.s.s.w.FilterChainProxy.doFilter(FilterChainProxy.java:186)\n\tat o.s.w.f.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)\n\tat o.s.w.f.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat o.a.c.c.ApplicationF...\n"}
{"timestamp":"2024-02-21 16:31:53.889","logger":"io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter","level":"ERROR","thread":"OkHttp http://localhost:4317/...","message":"Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317"}
{"timestamp":"2024-02-21 16:34:36.184","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"b5484aa97958fb9751db1c334d628a85","spanId":"d1eaa56cdcd76b08","message":"Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception","stack_trace":"k.c.j.c.e.GeneralClientException$UnauthorizedException: 계정 정보를 찾을 수 없습니다. id: null\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:16)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.h.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)\n\tat o.s.s.w.h.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.r.a.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.s.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)\n\tat o.s.s.w.FilterChainProxy.doFilter(FilterChainProxy.java:186)\n\tat o.s.w.f.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)\n\tat o.s.w.f.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter...\n"}
{"timestamp":"2024-02-21 16:34:36.218","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"b5484aa97958fb9751db1c334d628a85","spanId":"d1eaa56cdcd76b08","message":"Servlet.service() for servlet [dispatcherServlet] threw exception","stack_trace":"k.c.j.c.e.GeneralClientException$UnauthorizedException: 계정 정보를 찾을 수 없습니다. id: null\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:16)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)\n\tat o.s.s.w.FilterChainProxy.doFilter(FilterChainProxy.java:186)\n\tat o.s.w.f.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)\n\tat o.s.w.f.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat o.a.c.c.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)\n\tat o.s.w.f.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n...\n"}
{"timestamp":"2024-02-21 16:34:36.220","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost]","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"b5484aa97958fb9751db1c334d628a85","spanId":"d1eaa56cdcd76b08","message":"Exception Processing ErrorPage[errorCode=0, location=/error]","stack_trace":"k.c.j.c.e.GeneralClientException$UnauthorizedException: 계정 정보를 찾을 수 없습니다. id: null\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:16)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)\n\tat o.s.s.w.FilterChainProxy.doFilter(FilterChainProxy.java:186)\n\tat o.s.w.f.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)\n\tat o.s.w.f.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat o.a.c.c.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)\n\tat o.s.w.f.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n...\n"}
{"timestamp":"2024-02-21 16:39:15.212","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"77066f9dbe8038800535020980ddcb40","spanId":"487c44235f58569b","message":"Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Filter execution threw an exception] with root cause","stack_trace":"java.lang.Exception: User not found with id: null\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:15)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.h.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)\n\tat o.s.s.w.h.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.r.a.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.s.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)\n\tat o.s.s.w.FilterChainProxy.doFilter(FilterChainProxy.java:186)\n\tat o.s.w.f.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)\n\tat o.s.w.f.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)...\n"}
{"timestamp":"2024-02-21 16:39:15.243","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"77066f9dbe8038800535020980ddcb40","spanId":"487c44235f58569b","message":"Servlet.service() for servlet [dispatcherServlet] threw exception","stack_trace":"java.lang.Exception: User not found with id: null\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:15)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)\n\tat o.s.s.w.FilterChainProxy.doFilter(FilterChainProxy.java:186)\n\tat o.s.w.f.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)\n\tat o.s.w.f.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat o.a.c.c.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)\n\tat o.s.w.f.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat o.a.c.c.ApplicationFilterChai...\n"}
{"timestamp":"2024-02-21 16:39:15.244","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost]","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"77066f9dbe8038800535020980ddcb40","spanId":"487c44235f58569b","message":"Exception Processing ErrorPage[errorCode=0, location=/error]","stack_trace":"java.lang.Exception: User not found with id: null\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:15)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)\n\tat o.s.s.w.FilterChainProxy.doFilter(FilterChainProxy.java:186)\n\tat o.s.w.f.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)\n\tat o.s.w.f.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\t... 37 common frames omitted\nWrapped by: j.s.ServletException: Filter execution threw an exception\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)\n\tat o.a.c.c.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)\n\tat o.s.w.f.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n\tat o....\n"}
{"timestamp":"2024-02-21 16:39:15.322","logger":"io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter","level":"ERROR","thread":"OkHttp http://localhost:4317/...","message":"Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317"}
{"timestamp":"2024-02-21 16:43:55.401","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"d4e66bc854e2d9f1ce104416ac8179b5","spanId":"96f2bf55a84ae36c","message":"Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Filter execution threw an exception] with root cause","stack_trace":"java.lang.Exception: User not found with id: null\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:15)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.h.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)\n\tat o.s.s.w.h.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.r.a.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.s.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)\n\tat o.s.s.w.FilterChainProxy.doFilter(FilterChainProxy.java:186)\n\tat o.s.w.f.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)\n\tat o.s.w.f.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)...\n"}
{"timestamp":"2024-02-21 16:43:55.420","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"d4e66bc854e2d9f1ce104416ac8179b5","spanId":"96f2bf55a84ae36c","message":"Servlet.service() for servlet [dispatcherServlet] threw exception","stack_trace":"java.lang.Exception: User not found with id: null\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:15)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)\n\tat o.s.s.w.FilterChainProxy.doFilter(FilterChainProxy.java:186)\n\tat o.s.w.f.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)\n\tat o.s.w.f.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat o.a.c.c.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)\n\tat o.s.w.f.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat o.a.c.c.ApplicationFilterChai...\n"}
{"timestamp":"2024-02-21 16:43:55.421","logger":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost]","level":"ERROR","thread":"http-nio-11402-exec-1","traceId":"d4e66bc854e2d9f1ce104416ac8179b5","spanId":"96f2bf55a84ae36c","message":"Exception Processing ErrorPage[errorCode=0, location=/error]","stack_trace":"java.lang.Exception: User not found with id: null\n\tat k.c.j.d.u.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.kt:15)\n\tat k.c.j.c.j.JwtService.getAuthentication(JwtService.kt:56)\n\tat k.c.j.c.j.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.kt:40)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:103)\n\tat o.s.s.w.a.l.LogoutFilter.doFilter(LogoutFilter.java:89)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)\n\tat o.s.s.w.c.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)\n\tat o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)\n\tat o.s.s.w.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)\n\tat o.s.s.w.FilterChainProxy.doFilter(FilterChainProxy.java:186)\n\tat o.s.w.f.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)\n\tat o.s.w.f.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\t... 37 common frames omitted\nWrapped by: j.s.ServletException: Filter execution threw an exception\n\tat o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)\n\tat o.a.c.c.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)\n\tat o.s.w.f.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n\tat o....\n"}
